/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Animaciones;

import Clases_RRHH.Experiencia_Laboral;
import Clases_RRHH.Experiencia_Laboral_Detallada;
import Clases_RRHH.Puesto;

/**
 *
 * @author Langas
 */
public class Experiencia_Laboral_Ve extends javax.swing.JFrame {

    /**
     * Creates new form ExpLD
     */
    int x, y;

    public Experiencia_Laboral_Ve() {
        initComponents();

        //AWTUtilities.setWindowOpacity();
        Experiencia_Laboral ExpL = new Experiencia_Laboral(txt_id_ExpL, jLabel_id_Nombre_EpLLD, txt_Buscar_ExpL, tbl_ExpL);
        ExpL.Actualizar_Tabla();
        txt_id_Puesto.setVisible(false);
        txt_Nombre_Puesto.setVisible(false);
        txt_Estatus_Puesto.setVisible(false);
        txt_Descripcion_Puesto.setVisible(false);
        jComboBox_Nombre_EpLLD.setVisible(false);
        txt_id_ExpL.setVisible(false);
        jLabel_id_Nombre_EpLLD.setVisible(false);
        jScrollPane4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        ExpLD = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        Movimiento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_id_Puesto = new javax.swing.JTextField();
        txt_Nombre_Puesto = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_Descripcion_Puesto = new javax.swing.JTextArea();
        txt_Estatus_Puesto = new javax.swing.JTextField();
        icono_Buscar4 = new javax.swing.JLabel();
        jLabel_Buscar_ExpL = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        tbl_ExpL = new javax.swing.JTable();
        txt_Buscar_ExpL = new javax.swing.JTextField();
        jComboBox_Nombre_EpLLD = new javax.swing.JComboBox<>();
        jLabel_id_Nombre_EpLLD = new javax.swing.JLabel();
        txt_id_ExpL = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExpLD.setBackground(new java.awt.Color(28, 27, 33));
        ExpLD.setEnabled(false);
        ExpLD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Experiencia Laboral");
        ExpLD.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 280, 40));

        Movimiento.setBackground(new java.awt.Color(28, 27, 33));
        Movimiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovimientoMouseDragged(evt);
            }
        });
        Movimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovimientoMousePressed(evt);
            }
        });
        Movimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Movimiento.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 20, 30));

        ExpLD.add(Movimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 750, 40));

        txt_id_Puesto.setBackground(new java.awt.Color(231, 231, 231));
        txt_id_Puesto.setForeground(new java.awt.Color(153, 153, 153));
        txt_id_Puesto.setBorder(null);
        txt_id_Puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_PuestoActionPerformed(evt);
            }
        });
        ExpLD.add(txt_id_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 140, 20));

        txt_Nombre_Puesto.setBackground(new java.awt.Color(231, 231, 231));
        txt_Nombre_Puesto.setForeground(new java.awt.Color(153, 153, 153));
        txt_Nombre_Puesto.setBorder(null);
        txt_Nombre_Puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nombre_PuestoActionPerformed(evt);
            }
        });
        ExpLD.add(txt_Nombre_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 140, 20));

        txt_Descripcion_Puesto.setColumns(20);
        txt_Descripcion_Puesto.setRows(5);
        txt_Descripcion_Puesto.setAutoscrolls(false);
        jScrollPane4.setViewportView(txt_Descripcion_Puesto);

        ExpLD.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 180, 30));

        txt_Estatus_Puesto.setBackground(new java.awt.Color(231, 231, 231));
        txt_Estatus_Puesto.setForeground(new java.awt.Color(153, 153, 153));
        txt_Estatus_Puesto.setBorder(null);
        txt_Estatus_Puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Estatus_PuestoActionPerformed(evt);
            }
        });
        ExpLD.add(txt_Estatus_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 140, 20));

        icono_Buscar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_D.png"))); // NOI18N
        icono_Buscar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icono_Buscar4MouseClicked(evt);
            }
        });
        ExpLD.add(icono_Buscar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 20, 20));

        jLabel_Buscar_ExpL.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Buscar_ExpL.setText("Buscar");
        ExpLD.add(jLabel_Buscar_ExpL, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 40, 20));

        tbl_ExpL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_ExpL.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_ExpL.setSelectionBackground(new java.awt.Color(40, 41, 46));
        tbl_ExpL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ExpLMouseClicked(evt);
            }
        });
        jScrollPane25.setViewportView(tbl_ExpL);

        ExpLD.add(jScrollPane25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 600, 190));

        txt_Buscar_ExpL.setBackground(new java.awt.Color(40, 41, 46));
        txt_Buscar_ExpL.setForeground(new java.awt.Color(153, 153, 153));
        txt_Buscar_ExpL.setBorder(null);
        txt_Buscar_ExpL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Buscar_ExpLActionPerformed(evt);
            }
        });
        txt_Buscar_ExpL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Buscar_ExpLKeyReleased(evt);
            }
        });
        ExpLD.add(txt_Buscar_ExpL, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 290, 20));

        jComboBox_Nombre_EpLLD.setBackground(new java.awt.Color(40, 41, 46));
        jComboBox_Nombre_EpLLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Nombre_EpLLDActionPerformed(evt);
            }
        });
        ExpLD.add(jComboBox_Nombre_EpLLD, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 170, -1));

        jLabel_id_Nombre_EpLLD.setForeground(new java.awt.Color(255, 255, 255));
        ExpLD.add(jLabel_id_Nombre_EpLLD, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 40, 20));

        getContentPane().add(ExpLD, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, 800, 500));

        txt_id_ExpL.setBackground(new java.awt.Color(40, 41, 46));
        txt_id_ExpL.setForeground(new java.awt.Color(153, 153, 153));
        txt_id_ExpL.setBorder(null);
        txt_id_ExpL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_ExpLActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id_ExpL, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 180, 20));

        setBounds(0, 0, 747, 482);
    }// </editor-fold>//GEN-END:initComponents

    private void MovimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_MovimientoMousePressed

    private void MovimientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_MovimientoMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txt_id_PuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_PuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_PuestoActionPerformed

    private void txt_Nombre_PuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nombre_PuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nombre_PuestoActionPerformed

    private void txt_Estatus_PuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Estatus_PuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Estatus_PuestoActionPerformed

    private void txt_Buscar_ExpLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Buscar_ExpLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Buscar_ExpLActionPerformed

    private void txt_Buscar_ExpLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Buscar_ExpLKeyReleased
        // TODO add your handling code here:
        Experiencia_Laboral ExpL = new Experiencia_Laboral(txt_id_ExpL, jLabel_id_Nombre_EpLLD, txt_Buscar_ExpL, tbl_ExpL);
        ExpL.Buscar_ExpLF(txt_Buscar_ExpL.getText());
    }//GEN-LAST:event_txt_Buscar_ExpLKeyReleased

    private void icono_Buscar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icono_Buscar4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_icono_Buscar4MouseClicked

    private void tbl_ExpLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ExpLMouseClicked
        // TODO add your handling code here:
        int Seleccion = tbl_ExpL.rowAtPoint(evt.getPoint());
        txt_id_ExpL.setText(String.valueOf(tbl_ExpL.getValueAt(Seleccion, 0)));
        jLabel_id_Nombre_EpLLD.setText(String.valueOf(tbl_ExpL.getValueAt(Seleccion, 1)));

        Experiencia_Laboral ExpL = new Experiencia_Laboral(txt_id_ExpL, jLabel_id_Nombre_EpLLD, txt_Buscar_ExpL, tbl_ExpL);
        ExpL.BuscarFila_ExpL("nombre_tipo", "explab_detallado", "id_tipoexp", jComboBox_Nombre_EpLLD, jLabel_id_Nombre_EpLLD);
    }//GEN-LAST:event_tbl_ExpLMouseClicked

    private void txt_id_ExpLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_ExpLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_ExpLActionPerformed

    private void jComboBox_Nombre_EpLLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Nombre_EpLLDActionPerformed
        // TODO add your handling code here:
        Experiencia_Laboral ExpL = new Experiencia_Laboral(txt_id_ExpL, jLabel_id_Nombre_EpLLD, txt_Buscar_ExpL, tbl_ExpL);
        ExpL.EncontrarID_ExpLD("id_tipoexp", "explab_detallado", "nombre_tipo", jComboBox_Nombre_EpLLD);
    }//GEN-LAST:event_jComboBox_Nombre_EpLLDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Experiencia_Laboral_Ve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Experiencia_Laboral_Ve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Experiencia_Laboral_Ve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Experiencia_Laboral_Ve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Experiencia_Laboral_Ve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ExpLD;
    private javax.swing.JPanel Movimiento;
    private javax.swing.JLabel icono_Buscar4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox_Nombre_EpLLD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Buscar_ExpL;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_id_Nombre_EpLLD;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbl_ExpL;
    private javax.swing.JTextField txt_Buscar_ExpL;
    private javax.swing.JTextArea txt_Descripcion_Puesto;
    private javax.swing.JTextField txt_Estatus_Puesto;
    private javax.swing.JTextField txt_Nombre_Puesto;
    private javax.swing.JTextField txt_id_ExpL;
    private javax.swing.JTextField txt_id_Puesto;
    // End of variables declaration//GEN-END:variables
}
