/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Finanzas;

/**
 *
 * @author Brayan Cifuentes
 */
public class Bancos extends javax.swing.JFrame {

    /**
     * Creates new form Bancos
     */
    public Bancos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Bancos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Panel_MIMEC = new javax.swing.JPanel();
        jLabel_ModificarM = new javax.swing.JLabel();
        jLabel_EliminarM = new javax.swing.JLabel();
        jLabel_ConsultarM = new javax.swing.JLabel();
        jLabel_MantenimientoM = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Panel_MIMEC1 = new javax.swing.JPanel();
        jLabel_ModificarM1 = new javax.swing.JLabel();
        jLabel_EliminarM1 = new javax.swing.JLabel();
        jLabel_ConsultarM1 = new javax.swing.JLabel();
        jLabel_MantenimientoM1 = new javax.swing.JLabel();
        Panel_MIMECContable = new javax.swing.JPanel();
        jLabel_ModificarM2 = new javax.swing.JLabel();
        jLabel_EliminarM2 = new javax.swing.JLabel();
        jLabel_ConsultarM2 = new javax.swing.JLabel();
        jLabel_MantenimientoM2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Panel_MIMEDocumento = new javax.swing.JPanel();
        jLabel_ModificarM3 = new javax.swing.JLabel();
        jLabel_EliminarM3 = new javax.swing.JLabel();
        jLabel_ConsultarM3 = new javax.swing.JLabel();
        jLabel_MantenimientoM3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Panel_MIMEConcepto = new javax.swing.JPanel();
        jLabel_ModificarM4 = new javax.swing.JLabel();
        jLabel_EliminarM4 = new javax.swing.JLabel();
        jLabel_ConsultarM4 = new javax.swing.JLabel();
        jLabel_MantenimientoM4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Panel_MIMEMBE = new javax.swing.JPanel();
        jLabel_ModificarM5 = new javax.swing.JLabel();
        jLabel_EliminarM5 = new javax.swing.JLabel();
        jLabel_ConsultarM5 = new javax.swing.JLabel();
        jLabel_MantenimientoM5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Panel_MIMBD = new javax.swing.JPanel();
        jLabel_ModificarM6 = new javax.swing.JLabel();
        jLabel_EliminarM6 = new javax.swing.JLabel();
        jLabel_ConsultarM6 = new javax.swing.JLabel();
        jLabel_MantenimientoM6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Panel_MIMFP = new javax.swing.JPanel();
        jLabel_ModificarM7 = new javax.swing.JLabel();
        jLabel_EliminarM7 = new javax.swing.JLabel();
        jLabel_ConsultarM7 = new javax.swing.JLabel();
        jLabel_MantenimientoM7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Panel_MB = new javax.swing.JPanel();
        jLabel_ModificarM8 = new javax.swing.JLabel();
        jLabel_EliminarM8 = new javax.swing.JLabel();
        jLabel_ConsultarM8 = new javax.swing.JLabel();
        jLabel_MantenimientoM8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Panel_MCBEnc = new javax.swing.JPanel();
        jLabel_ModificarM9 = new javax.swing.JLabel();
        jLabel_EliminarM9 = new javax.swing.JLabel();
        jLabel_ConsultarM9 = new javax.swing.JLabel();
        jLabel_MantenimientoM9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Panel_MCBEnc1 = new javax.swing.JPanel();
        jLabel_ModificarM10 = new javax.swing.JLabel();
        jLabel_EliminarM10 = new javax.swing.JLabel();
        jLabel_ConsultarM10 = new javax.swing.JLabel();
        jLabel_MantenimientoM10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Bancos.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Bancos.setPreferredSize(new java.awt.Dimension(1470, 680));
        Panel_Bancos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bancos");
        Panel_Bancos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 78, -1));

        jLabel2.setText("Moneda");
        Panel_Bancos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 78, -1));

        Panel_MIMEC.setBackground(new java.awt.Color(255, 255, 255));
        Panel_MIMEC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_MIMEC.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_MIMECMouseDragged(evt);
            }
        });
        Panel_MIMEC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_MIMECMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel_MIMECMouseReleased(evt);
            }
        });
        Panel_MIMEC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ModificarM.setText("Modificar Moneda");
        jLabel_ModificarM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ModificarM.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ModificarMMouseMoved(evt);
            }
        });
        jLabel_ModificarM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ModificarMMouseExited(evt);
            }
        });
        Panel_MIMEC.add(jLabel_ModificarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel_EliminarM.setText("Eliminar Moneda");
        jLabel_EliminarM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_EliminarM.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_EliminarMMouseMoved(evt);
            }
        });
        jLabel_EliminarM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_EliminarMMouseExited(evt);
            }
        });
        Panel_MIMEC.add(jLabel_EliminarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel_ConsultarM.setText("Consultar Moneda");
        jLabel_ConsultarM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ConsultarM.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarMMouseMoved(evt);
            }
        });
        jLabel_ConsultarM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarMMouseExited(evt);
            }
        });
        Panel_MIMEC.add(jLabel_ConsultarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel_MantenimientoM.setText("Mantenimiento Moneda");
        jLabel_MantenimientoM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MantenimientoM.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoMMouseMoved(evt);
            }
        });
        jLabel_MantenimientoM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoMMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoMMouseExited(evt);
            }
        });
        Panel_MIMEC.add(jLabel_MantenimientoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 180, -1));

        Panel_Bancos.add(Panel_MIMEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, 100));

        jLabel3.setText("Clasificacion Cuenta");
        Panel_Bancos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 130, -1));

        Panel_MIMEC1.setBackground(new java.awt.Color(255, 255, 255));
        Panel_MIMEC1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_MIMEC1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_MIMEC1MouseDragged(evt);
            }
        });
        Panel_MIMEC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_MIMEC1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel_MIMEC1MouseReleased(evt);
            }
        });
        Panel_MIMEC1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ModificarM1.setText("Modificar Moneda");
        jLabel_ModificarM1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ModificarM1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM1MouseMoved(evt);
            }
        });
        jLabel_ModificarM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM1MouseExited(evt);
            }
        });
        Panel_MIMEC1.add(jLabel_ModificarM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel_EliminarM1.setText("Eliminar Moneda");
        jLabel_EliminarM1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_EliminarM1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM1MouseMoved(evt);
            }
        });
        jLabel_EliminarM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM1MouseExited(evt);
            }
        });
        Panel_MIMEC1.add(jLabel_EliminarM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel_ConsultarM1.setText("Consultar Moneda");
        jLabel_ConsultarM1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ConsultarM1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM1MouseMoved(evt);
            }
        });
        jLabel_ConsultarM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM1MouseExited(evt);
            }
        });
        Panel_MIMEC1.add(jLabel_ConsultarM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel_MantenimientoM1.setText("Mantenimiento Clasificacion Cuenta");
        jLabel_MantenimientoM1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MantenimientoM1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM1MouseMoved(evt);
            }
        });
        jLabel_MantenimientoM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM1MouseExited(evt);
            }
        });
        Panel_MIMEC1.add(jLabel_MantenimientoM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, -1));

        Panel_Bancos.add(Panel_MIMEC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 210, 100));

        Panel_MIMECContable.setBackground(new java.awt.Color(255, 255, 255));
        Panel_MIMECContable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_MIMECContable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_MIMECContableMouseDragged(evt);
            }
        });
        Panel_MIMECContable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_MIMECContableMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel_MIMECContableMouseReleased(evt);
            }
        });
        Panel_MIMECContable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ModificarM2.setText("Modificar Moneda");
        jLabel_ModificarM2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ModificarM2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM2MouseMoved(evt);
            }
        });
        jLabel_ModificarM2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM2MouseExited(evt);
            }
        });
        Panel_MIMECContable.add(jLabel_ModificarM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel_EliminarM2.setText("Eliminar Moneda");
        jLabel_EliminarM2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_EliminarM2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM2MouseMoved(evt);
            }
        });
        jLabel_EliminarM2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM2MouseExited(evt);
            }
        });
        Panel_MIMECContable.add(jLabel_EliminarM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel_ConsultarM2.setText("Consultar Moneda");
        jLabel_ConsultarM2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ConsultarM2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM2MouseMoved(evt);
            }
        });
        jLabel_ConsultarM2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM2MouseExited(evt);
            }
        });
        Panel_MIMECContable.add(jLabel_ConsultarM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel_MantenimientoM2.setText("Mantenimiento Cuenta Contable");
        jLabel_MantenimientoM2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MantenimientoM2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM2MouseMoved(evt);
            }
        });
        jLabel_MantenimientoM2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM2MouseExited(evt);
            }
        });
        Panel_MIMECContable.add(jLabel_MantenimientoM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 180, -1));

        Panel_Bancos.add(Panel_MIMECContable, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 190, 100));

        jLabel4.setText("Cuenta Contable");
        Panel_Bancos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 100, -1));

        jLabel5.setText("Documento Bancario");
        Panel_Bancos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 70, 130, -1));

        Panel_MIMEDocumento.setBackground(new java.awt.Color(255, 255, 255));
        Panel_MIMEDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_MIMEDocumento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_MIMEDocumentoMouseDragged(evt);
            }
        });
        Panel_MIMEDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_MIMEDocumentoMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel_MIMEDocumentoMouseReleased(evt);
            }
        });
        Panel_MIMEDocumento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ModificarM3.setText("Modificar Moneda");
        jLabel_ModificarM3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ModificarM3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM3MouseMoved(evt);
            }
        });
        jLabel_ModificarM3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM3MouseExited(evt);
            }
        });
        Panel_MIMEDocumento.add(jLabel_ModificarM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel_EliminarM3.setText("Eliminar Moneda");
        jLabel_EliminarM3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_EliminarM3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM3MouseMoved(evt);
            }
        });
        jLabel_EliminarM3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM3MouseExited(evt);
            }
        });
        Panel_MIMEDocumento.add(jLabel_EliminarM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel_ConsultarM3.setText("Consultar Moneda");
        jLabel_ConsultarM3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ConsultarM3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM3MouseMoved(evt);
            }
        });
        jLabel_ConsultarM3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM3MouseExited(evt);
            }
        });
        Panel_MIMEDocumento.add(jLabel_ConsultarM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel_MantenimientoM3.setText("Mantenimiento Doc Bancario ");
        jLabel_MantenimientoM3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MantenimientoM3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM3MouseMoved(evt);
            }
        });
        jLabel_MantenimientoM3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM3MouseExited(evt);
            }
        });
        Panel_MIMEDocumento.add(jLabel_MantenimientoM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, -1));

        Panel_Bancos.add(Panel_MIMEDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 60, 190, 100));

        jLabel6.setText("Concepto Bancario");
        Panel_Bancos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, -1));

        Panel_MIMEConcepto.setBackground(new java.awt.Color(255, 255, 255));
        Panel_MIMEConcepto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_MIMEConcepto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_MIMEConceptoMouseDragged(evt);
            }
        });
        Panel_MIMEConcepto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_MIMEConceptoMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel_MIMEConceptoMouseReleased(evt);
            }
        });
        Panel_MIMEConcepto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ModificarM4.setText("Modificar Moneda");
        jLabel_ModificarM4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ModificarM4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM4MouseMoved(evt);
            }
        });
        jLabel_ModificarM4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM4MouseExited(evt);
            }
        });
        Panel_MIMEConcepto.add(jLabel_ModificarM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel_EliminarM4.setText("Eliminar Moneda");
        jLabel_EliminarM4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_EliminarM4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM4MouseMoved(evt);
            }
        });
        jLabel_EliminarM4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM4MouseExited(evt);
            }
        });
        Panel_MIMEConcepto.add(jLabel_EliminarM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel_ConsultarM4.setText("Consultar Moneda");
        jLabel_ConsultarM4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ConsultarM4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM4MouseMoved(evt);
            }
        });
        jLabel_ConsultarM4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM4MouseExited(evt);
            }
        });
        Panel_MIMEConcepto.add(jLabel_ConsultarM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel_MantenimientoM4.setText("Mantenimiento Concepto Bancario");
        jLabel_MantenimientoM4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MantenimientoM4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM4MouseMoved(evt);
            }
        });
        jLabel_MantenimientoM4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM4MouseExited(evt);
            }
        });
        Panel_MIMEConcepto.add(jLabel_MantenimientoM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, -1));

        Panel_Bancos.add(Panel_MIMEConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 220, 100));

        jLabel7.setText("Mov Ban Enc");
        Panel_Bancos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 80, -1));

        Panel_MIMEMBE.setBackground(new java.awt.Color(255, 255, 255));
        Panel_MIMEMBE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_MIMEMBE.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_MIMEMBEMouseDragged(evt);
            }
        });
        Panel_MIMEMBE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_MIMEMBEMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel_MIMEMBEMouseReleased(evt);
            }
        });
        Panel_MIMEMBE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ModificarM5.setText("Modificar Moneda");
        jLabel_ModificarM5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ModificarM5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM5MouseMoved(evt);
            }
        });
        jLabel_ModificarM5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM5MouseExited(evt);
            }
        });
        Panel_MIMEMBE.add(jLabel_ModificarM5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel_EliminarM5.setText("Eliminar Moneda");
        jLabel_EliminarM5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_EliminarM5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM5MouseMoved(evt);
            }
        });
        jLabel_EliminarM5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM5MouseExited(evt);
            }
        });
        Panel_MIMEMBE.add(jLabel_EliminarM5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel_ConsultarM5.setText("Consultar Moneda");
        jLabel_ConsultarM5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ConsultarM5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM5MouseMoved(evt);
            }
        });
        jLabel_ConsultarM5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM5MouseExited(evt);
            }
        });
        Panel_MIMEMBE.add(jLabel_ConsultarM5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel_MantenimientoM5.setText("Mantenimiento Ban Enc");
        jLabel_MantenimientoM5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MantenimientoM5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM5MouseMoved(evt);
            }
        });
        jLabel_MantenimientoM5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM5MouseExited(evt);
            }
        });
        Panel_MIMEMBE.add(jLabel_MantenimientoM5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));

        Panel_Bancos.add(Panel_MIMEMBE, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 150, 100));

        jLabel8.setText("Mov Ban Detalle");
        Panel_Bancos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 90, -1));

        Panel_MIMBD.setBackground(new java.awt.Color(255, 255, 255));
        Panel_MIMBD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_MIMBD.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_MIMBDMouseDragged(evt);
            }
        });
        Panel_MIMBD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_MIMBDMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel_MIMBDMouseReleased(evt);
            }
        });
        Panel_MIMBD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ModificarM6.setText("Modificar Moneda");
        jLabel_ModificarM6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ModificarM6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM6MouseMoved(evt);
            }
        });
        jLabel_ModificarM6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM6MouseExited(evt);
            }
        });
        Panel_MIMBD.add(jLabel_ModificarM6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel_EliminarM6.setText("Eliminar Moneda");
        jLabel_EliminarM6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_EliminarM6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM6MouseMoved(evt);
            }
        });
        jLabel_EliminarM6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM6MouseExited(evt);
            }
        });
        Panel_MIMBD.add(jLabel_EliminarM6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel_ConsultarM6.setText("Consultar Moneda");
        jLabel_ConsultarM6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ConsultarM6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM6MouseMoved(evt);
            }
        });
        jLabel_ConsultarM6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM6MouseExited(evt);
            }
        });
        Panel_MIMBD.add(jLabel_ConsultarM6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel_MantenimientoM6.setText("Mantenimiento Mov Ban Det");
        jLabel_MantenimientoM6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MantenimientoM6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM6MouseMoved(evt);
            }
        });
        jLabel_MantenimientoM6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM6MouseExited(evt);
            }
        });
        Panel_MIMBD.add(jLabel_MantenimientoM6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, -1));

        Panel_Bancos.add(Panel_MIMBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 180, 100));

        jLabel9.setText("Forma de Pago ");
        Panel_Bancos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 200, 90, -1));

        Panel_MIMFP.setBackground(new java.awt.Color(255, 255, 255));
        Panel_MIMFP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_MIMFP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_MIMFPMouseDragged(evt);
            }
        });
        Panel_MIMFP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_MIMFPMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel_MIMFPMouseReleased(evt);
            }
        });
        Panel_MIMFP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ModificarM7.setText("Modificar Moneda");
        jLabel_ModificarM7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ModificarM7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM7MouseMoved(evt);
            }
        });
        jLabel_ModificarM7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM7MouseExited(evt);
            }
        });
        Panel_MIMFP.add(jLabel_ModificarM7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel_EliminarM7.setText("Eliminar Moneda");
        jLabel_EliminarM7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_EliminarM7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM7MouseMoved(evt);
            }
        });
        jLabel_EliminarM7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM7MouseExited(evt);
            }
        });
        Panel_MIMFP.add(jLabel_EliminarM7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel_ConsultarM7.setText("Consultar Moneda");
        jLabel_ConsultarM7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ConsultarM7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM7MouseMoved(evt);
            }
        });
        jLabel_ConsultarM7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM7MouseExited(evt);
            }
        });
        Panel_MIMFP.add(jLabel_ConsultarM7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel_MantenimientoM7.setText("Mantenimiento Forma de Pago ");
        jLabel_MantenimientoM7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MantenimientoM7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM7MouseMoved(evt);
            }
        });
        jLabel_MantenimientoM7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM7MouseExited(evt);
            }
        });
        Panel_MIMFP.add(jLabel_MantenimientoM7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, -1));

        Panel_Bancos.add(Panel_MIMFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 190, 180, 100));

        jLabel10.setText("Banco ");
        Panel_Bancos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 60, -1));

        Panel_MB.setBackground(new java.awt.Color(255, 255, 255));
        Panel_MB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_MB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_MBMouseDragged(evt);
            }
        });
        Panel_MB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_MBMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel_MBMouseReleased(evt);
            }
        });
        Panel_MB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ModificarM8.setText("Modificar Moneda");
        jLabel_ModificarM8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ModificarM8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM8MouseMoved(evt);
            }
        });
        jLabel_ModificarM8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM8MouseExited(evt);
            }
        });
        Panel_MB.add(jLabel_ModificarM8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel_EliminarM8.setText("Eliminar Moneda");
        jLabel_EliminarM8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_EliminarM8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM8MouseMoved(evt);
            }
        });
        jLabel_EliminarM8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM8MouseExited(evt);
            }
        });
        Panel_MB.add(jLabel_EliminarM8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel_ConsultarM8.setText("Consultar Moneda");
        jLabel_ConsultarM8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ConsultarM8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM8MouseMoved(evt);
            }
        });
        jLabel_ConsultarM8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM8MouseExited(evt);
            }
        });
        Panel_MB.add(jLabel_ConsultarM8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel_MantenimientoM8.setText("Mantenimiento Banco");
        jLabel_MantenimientoM8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MantenimientoM8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM8MouseMoved(evt);
            }
        });
        jLabel_MantenimientoM8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM8MouseExited(evt);
            }
        });
        Panel_MB.add(jLabel_MantenimientoM8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, -1));

        Panel_Bancos.add(Panel_MB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 130, 100));

        jLabel11.setText("Conciliacion Ban Enc");
        Panel_Bancos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 120, -1));

        Panel_MCBEnc.setBackground(new java.awt.Color(255, 255, 255));
        Panel_MCBEnc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_MCBEnc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_MCBEncMouseDragged(evt);
            }
        });
        Panel_MCBEnc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_MCBEncMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel_MCBEncMouseReleased(evt);
            }
        });
        Panel_MCBEnc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ModificarM9.setText("Modificar Moneda");
        jLabel_ModificarM9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ModificarM9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM9MouseMoved(evt);
            }
        });
        jLabel_ModificarM9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM9MouseExited(evt);
            }
        });
        Panel_MCBEnc.add(jLabel_ModificarM9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel_EliminarM9.setText("Eliminar Moneda");
        jLabel_EliminarM9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_EliminarM9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM9MouseMoved(evt);
            }
        });
        jLabel_EliminarM9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM9MouseExited(evt);
            }
        });
        Panel_MCBEnc.add(jLabel_EliminarM9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel_ConsultarM9.setText("Consultar Moneda");
        jLabel_ConsultarM9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ConsultarM9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM9MouseMoved(evt);
            }
        });
        jLabel_ConsultarM9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM9MouseExited(evt);
            }
        });
        Panel_MCBEnc.add(jLabel_ConsultarM9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel_MantenimientoM9.setText("Mantenimiento Conc Ban Enc");
        jLabel_MantenimientoM9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MantenimientoM9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM9MouseMoved(evt);
            }
        });
        jLabel_MantenimientoM9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM9MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM9MouseExited(evt);
            }
        });
        Panel_MCBEnc.add(jLabel_MantenimientoM9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 180, -1));

        Panel_Bancos.add(Panel_MCBEnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 180, 100));

        jLabel12.setText("Conciliacion Ban Det");
        Panel_Bancos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 120, -1));

        Panel_MCBEnc1.setBackground(new java.awt.Color(255, 255, 255));
        Panel_MCBEnc1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_MCBEnc1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_MCBEnc1MouseDragged(evt);
            }
        });
        Panel_MCBEnc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_MCBEnc1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel_MCBEnc1MouseReleased(evt);
            }
        });
        Panel_MCBEnc1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ModificarM10.setText("Modificar Moneda");
        jLabel_ModificarM10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ModificarM10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM10MouseMoved(evt);
            }
        });
        jLabel_ModificarM10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ModificarM10MouseExited(evt);
            }
        });
        Panel_MCBEnc1.add(jLabel_ModificarM10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel_EliminarM10.setText("Eliminar Moneda");
        jLabel_EliminarM10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_EliminarM10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM10MouseMoved(evt);
            }
        });
        jLabel_EliminarM10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_EliminarM10MouseExited(evt);
            }
        });
        Panel_MCBEnc1.add(jLabel_EliminarM10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel_ConsultarM10.setText("Consultar Moneda");
        jLabel_ConsultarM10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ConsultarM10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM10MouseMoved(evt);
            }
        });
        jLabel_ConsultarM10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ConsultarM10MouseExited(evt);
            }
        });
        Panel_MCBEnc1.add(jLabel_ConsultarM10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel_MantenimientoM10.setText("Mantenimiento Conc Ban Det");
        jLabel_MantenimientoM10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MantenimientoM10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM10MouseMoved(evt);
            }
        });
        jLabel_MantenimientoM10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM10MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MantenimientoM10MouseExited(evt);
            }
        });
        Panel_MCBEnc1.add(jLabel_MantenimientoM10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        Panel_Bancos.add(Panel_MCBEnc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 180, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Bancos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Bancos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Panel_MIMEC1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMEC1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMEC1MouseReleased

    private void Panel_MIMEC1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMEC1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMEC1MouseExited

    private void Panel_MIMEC1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMEC1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMEC1MouseDragged

    private void jLabel_MantenimientoM1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM1MouseExited

    private void jLabel_MantenimientoM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM1MouseClicked

    private void jLabel_MantenimientoM1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM1MouseMoved

    private void jLabel_ConsultarM1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM1MouseExited

    private void jLabel_ConsultarM1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM1MouseMoved

    private void jLabel_EliminarM1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM1MouseExited

    private void jLabel_EliminarM1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM1MouseMoved

    private void jLabel_ModificarM1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM1MouseExited

    private void jLabel_ModificarM1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM1MouseMoved

    private void Panel_MIMECMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMECMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMECMouseReleased

    private void Panel_MIMECMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMECMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Panel_MIMECMouseExited

    private void Panel_MIMECMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMECMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMECMouseDragged

    private void jLabel_MantenimientoMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoMMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoMMouseExited

    private void jLabel_MantenimientoMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoMMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel_MantenimientoMMouseClicked

    private void jLabel_MantenimientoMMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoMMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoMMouseMoved

    private void jLabel_ConsultarMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarMMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarMMouseExited

    private void jLabel_ConsultarMMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarMMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel_ConsultarMMouseMoved

    private void jLabel_EliminarMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarMMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarMMouseExited

    private void jLabel_EliminarMMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarMMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel_EliminarMMouseMoved

    private void jLabel_ModificarMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarMMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarMMouseExited

    private void jLabel_ModificarMMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarMMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel_ModificarMMouseMoved

    private void jLabel_ModificarM2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM2MouseMoved

    private void jLabel_ModificarM2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM2MouseExited

    private void jLabel_EliminarM2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM2MouseMoved

    private void jLabel_EliminarM2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM2MouseExited

    private void jLabel_ConsultarM2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM2MouseMoved

    private void jLabel_ConsultarM2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM2MouseExited

    private void jLabel_MantenimientoM2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM2MouseMoved

    private void jLabel_MantenimientoM2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM2MouseClicked

    private void jLabel_MantenimientoM2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM2MouseExited

    private void Panel_MIMECContableMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMECContableMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMECContableMouseDragged

    private void Panel_MIMECContableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMECContableMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMECContableMouseExited

    private void Panel_MIMECContableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMECContableMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMECContableMouseReleased

    private void jLabel_ModificarM3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM3MouseMoved

    private void jLabel_ModificarM3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM3MouseExited

    private void jLabel_EliminarM3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM3MouseMoved

    private void jLabel_EliminarM3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM3MouseExited

    private void jLabel_ConsultarM3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM3MouseMoved

    private void jLabel_ConsultarM3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM3MouseExited

    private void jLabel_MantenimientoM3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM3MouseMoved

    private void jLabel_MantenimientoM3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM3MouseClicked

    private void jLabel_MantenimientoM3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM3MouseExited

    private void Panel_MIMEDocumentoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMEDocumentoMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMEDocumentoMouseDragged

    private void Panel_MIMEDocumentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMEDocumentoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMEDocumentoMouseExited

    private void Panel_MIMEDocumentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMEDocumentoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMEDocumentoMouseReleased

    private void jLabel_ModificarM4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM4MouseMoved

    private void jLabel_ModificarM4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM4MouseExited

    private void jLabel_EliminarM4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM4MouseMoved

    private void jLabel_EliminarM4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM4MouseExited

    private void jLabel_ConsultarM4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM4MouseMoved

    private void jLabel_ConsultarM4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM4MouseExited

    private void jLabel_MantenimientoM4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM4MouseMoved

    private void jLabel_MantenimientoM4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM4MouseClicked

    private void jLabel_MantenimientoM4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM4MouseExited

    private void Panel_MIMEConceptoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMEConceptoMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMEConceptoMouseDragged

    private void Panel_MIMEConceptoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMEConceptoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMEConceptoMouseExited

    private void Panel_MIMEConceptoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMEConceptoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMEConceptoMouseReleased

    private void jLabel_ModificarM5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM5MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM5MouseMoved

    private void jLabel_ModificarM5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM5MouseExited

    private void jLabel_EliminarM5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM5MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM5MouseMoved

    private void jLabel_EliminarM5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM5MouseExited

    private void jLabel_ConsultarM5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM5MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM5MouseMoved

    private void jLabel_ConsultarM5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM5MouseExited

    private void jLabel_MantenimientoM5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM5MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM5MouseMoved

    private void jLabel_MantenimientoM5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM5MouseClicked

    private void jLabel_MantenimientoM5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM5MouseExited

    private void Panel_MIMEMBEMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMEMBEMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMEMBEMouseDragged

    private void Panel_MIMEMBEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMEMBEMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMEMBEMouseExited

    private void Panel_MIMEMBEMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMEMBEMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMEMBEMouseReleased

    private void jLabel_ModificarM6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM6MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM6MouseMoved

    private void jLabel_ModificarM6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM6MouseExited

    private void jLabel_EliminarM6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM6MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM6MouseMoved

    private void jLabel_EliminarM6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM6MouseExited

    private void jLabel_ConsultarM6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM6MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM6MouseMoved

    private void jLabel_ConsultarM6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM6MouseExited

    private void jLabel_MantenimientoM6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM6MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM6MouseMoved

    private void jLabel_MantenimientoM6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM6MouseClicked

    private void jLabel_MantenimientoM6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM6MouseExited

    private void Panel_MIMBDMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMBDMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMBDMouseDragged

    private void Panel_MIMBDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMBDMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMBDMouseExited

    private void Panel_MIMBDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMBDMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMBDMouseReleased

    private void jLabel_ModificarM7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM7MouseMoved

    private void jLabel_ModificarM7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM7MouseExited

    private void jLabel_EliminarM7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM7MouseMoved

    private void jLabel_EliminarM7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM7MouseExited

    private void jLabel_ConsultarM7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM7MouseMoved

    private void jLabel_ConsultarM7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM7MouseExited

    private void jLabel_MantenimientoM7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM7MouseMoved

    private void jLabel_MantenimientoM7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM7MouseClicked

    private void jLabel_MantenimientoM7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM7MouseExited

    private void Panel_MIMFPMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMFPMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMFPMouseDragged

    private void Panel_MIMFPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMFPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMFPMouseExited

    private void Panel_MIMFPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MIMFPMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MIMFPMouseReleased

    private void jLabel_ModificarM8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM8MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM8MouseMoved

    private void jLabel_ModificarM8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM8MouseExited

    private void jLabel_EliminarM8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM8MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM8MouseMoved

    private void jLabel_EliminarM8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM8MouseExited

    private void jLabel_ConsultarM8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM8MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM8MouseMoved

    private void jLabel_ConsultarM8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM8MouseExited

    private void jLabel_MantenimientoM8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM8MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM8MouseMoved

    private void jLabel_MantenimientoM8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM8MouseClicked

    private void jLabel_MantenimientoM8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM8MouseExited

    private void Panel_MBMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MBMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MBMouseDragged

    private void Panel_MBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MBMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MBMouseExited

    private void Panel_MBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MBMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MBMouseReleased

    private void jLabel_ModificarM9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM9MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM9MouseMoved

    private void jLabel_ModificarM9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM9MouseExited

    private void jLabel_EliminarM9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM9MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM9MouseMoved

    private void jLabel_EliminarM9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM9MouseExited

    private void jLabel_ConsultarM9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM9MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM9MouseMoved

    private void jLabel_ConsultarM9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM9MouseExited

    private void jLabel_MantenimientoM9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM9MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM9MouseMoved

    private void jLabel_MantenimientoM9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM9MouseClicked

    private void jLabel_MantenimientoM9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM9MouseExited

    private void Panel_MCBEncMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MCBEncMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MCBEncMouseDragged

    private void Panel_MCBEncMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MCBEncMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MCBEncMouseExited

    private void Panel_MCBEncMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MCBEncMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MCBEncMouseReleased

    private void jLabel_ModificarM10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM10MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM10MouseMoved

    private void jLabel_ModificarM10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ModificarM10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ModificarM10MouseExited

    private void jLabel_EliminarM10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM10MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM10MouseMoved

    private void jLabel_EliminarM10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EliminarM10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_EliminarM10MouseExited

    private void jLabel_ConsultarM10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM10MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM10MouseMoved

    private void jLabel_ConsultarM10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConsultarM10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ConsultarM10MouseExited

    private void jLabel_MantenimientoM10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM10MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM10MouseMoved

    private void jLabel_MantenimientoM10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM10MouseClicked

    private void jLabel_MantenimientoM10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MantenimientoM10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MantenimientoM10MouseExited

    private void Panel_MCBEnc1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MCBEnc1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MCBEnc1MouseDragged

    private void Panel_MCBEnc1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MCBEnc1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MCBEnc1MouseExited

    private void Panel_MCBEnc1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MCBEnc1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_MCBEnc1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bancos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Bancos;
    private javax.swing.JPanel Panel_MB;
    private javax.swing.JPanel Panel_MCBEnc;
    private javax.swing.JPanel Panel_MCBEnc1;
    private javax.swing.JPanel Panel_MIMBD;
    private javax.swing.JPanel Panel_MIMEC;
    private javax.swing.JPanel Panel_MIMEC1;
    private javax.swing.JPanel Panel_MIMECContable;
    private javax.swing.JPanel Panel_MIMEConcepto;
    private javax.swing.JPanel Panel_MIMEDocumento;
    private javax.swing.JPanel Panel_MIMEMBE;
    private javax.swing.JPanel Panel_MIMFP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_ConsultarM;
    private javax.swing.JLabel jLabel_ConsultarM1;
    private javax.swing.JLabel jLabel_ConsultarM10;
    private javax.swing.JLabel jLabel_ConsultarM2;
    private javax.swing.JLabel jLabel_ConsultarM3;
    private javax.swing.JLabel jLabel_ConsultarM4;
    private javax.swing.JLabel jLabel_ConsultarM5;
    private javax.swing.JLabel jLabel_ConsultarM6;
    private javax.swing.JLabel jLabel_ConsultarM7;
    private javax.swing.JLabel jLabel_ConsultarM8;
    private javax.swing.JLabel jLabel_ConsultarM9;
    private javax.swing.JLabel jLabel_EliminarM;
    private javax.swing.JLabel jLabel_EliminarM1;
    private javax.swing.JLabel jLabel_EliminarM10;
    private javax.swing.JLabel jLabel_EliminarM2;
    private javax.swing.JLabel jLabel_EliminarM3;
    private javax.swing.JLabel jLabel_EliminarM4;
    private javax.swing.JLabel jLabel_EliminarM5;
    private javax.swing.JLabel jLabel_EliminarM6;
    private javax.swing.JLabel jLabel_EliminarM7;
    private javax.swing.JLabel jLabel_EliminarM8;
    private javax.swing.JLabel jLabel_EliminarM9;
    private javax.swing.JLabel jLabel_MantenimientoM;
    private javax.swing.JLabel jLabel_MantenimientoM1;
    private javax.swing.JLabel jLabel_MantenimientoM10;
    private javax.swing.JLabel jLabel_MantenimientoM2;
    private javax.swing.JLabel jLabel_MantenimientoM3;
    private javax.swing.JLabel jLabel_MantenimientoM4;
    private javax.swing.JLabel jLabel_MantenimientoM5;
    private javax.swing.JLabel jLabel_MantenimientoM6;
    private javax.swing.JLabel jLabel_MantenimientoM7;
    private javax.swing.JLabel jLabel_MantenimientoM8;
    private javax.swing.JLabel jLabel_MantenimientoM9;
    private javax.swing.JLabel jLabel_ModificarM;
    private javax.swing.JLabel jLabel_ModificarM1;
    private javax.swing.JLabel jLabel_ModificarM10;
    private javax.swing.JLabel jLabel_ModificarM2;
    private javax.swing.JLabel jLabel_ModificarM3;
    private javax.swing.JLabel jLabel_ModificarM4;
    private javax.swing.JLabel jLabel_ModificarM5;
    private javax.swing.JLabel jLabel_ModificarM6;
    private javax.swing.JLabel jLabel_ModificarM7;
    private javax.swing.JLabel jLabel_ModificarM8;
    private javax.swing.JLabel jLabel_ModificarM9;
    // End of variables declaration//GEN-END:variables
}
