/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Finanzas;

import static Finanzas_Clases.Departamento.Base_de_Datos;
import static Finanzas_Clases.Departamento.Clave;
import static Finanzas_Clases.Departamento.Usuario;
import com.mysql.jdbc.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Geovani
 */
public class Login extends javax.swing.JFrame {

   

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

        jPanelTransparente1.setVisible(true);
        jPanelTransparente_Nuevo.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEImagePanel1 = new LIB.JEImagePanel();
        jPanelTransparente_Nuevo = new LIB.JPanelTransparente();
        jTexfieldPH_FielTex2 = new LIB.JTexfieldPH_FielTex();
        jTexfieldPH_Password2 = new LIB.JTexfieldPH_Password();
        jPanelRound4 = new LIB.JPanelRound();
        lbl_Ingresar2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelRound5 = new LIB.JPanelRound();
        lbl_Ingresar3 = new javax.swing.JLabel();
        jPanelRound6 = new LIB.JPanelRound();
        lbl_Registrar1 = new javax.swing.JLabel();
        lbl_Cerrar1 = new javax.swing.JLabel();
        jPanelTransparente1 = new LIB.JPanelTransparente();
        jTexfieldPH_FielTex1 = new LIB.JTexfieldPH_FielTex();
        jTexfieldPH_Password1 = new LIB.JTexfieldPH_Password();
        jPanelRound1 = new LIB.JPanelRound();
        lbl_Ingresar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelRound2 = new LIB.JPanelRound();
        lbl_Ingresar1 = new javax.swing.JLabel();
        jPanelRound3 = new LIB.JPanelRound();
        lbl_Registrar = new javax.swing.JLabel();
        lbl_Cerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_Hotel.jpg"))); // NOI18N
        jEImagePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTransparente_Nuevo.setColorPrimario(new java.awt.Color(107, 41, 29));
        jPanelTransparente_Nuevo.setColorSecundario(new java.awt.Color(134, 124, 112));
        jPanelTransparente_Nuevo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTexfieldPH_FielTex2.setBorder(null);
        jTexfieldPH_FielTex2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexfieldPH_FielTex2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTexfieldPH_FielTex2.setPlaceholder("User Name");
        jPanelTransparente_Nuevo.add(jTexfieldPH_FielTex2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jTexfieldPH_Password2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexfieldPH_Password2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTexfieldPH_Password2.setPlaceholder("Password");
        jPanelTransparente_Nuevo.add(jTexfieldPH_Password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jPanelRound4.setColorPrimario(new java.awt.Color(107, 41, 29));
        jPanelRound4.setColorSecundario(new java.awt.Color(134, 124, 112));

        lbl_Ingresar2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lbl_Ingresar2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ingresar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ingresar2.setText("Create");
        lbl_Ingresar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Ingresar2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRound4Layout = new javax.swing.GroupLayout(jPanelRound4);
        jPanelRound4.setLayout(jPanelRound4Layout);
        jPanelRound4Layout.setHorizontalGroup(
            jPanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound4Layout.createSequentialGroup()
                .addComponent(lbl_Ingresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelRound4Layout.setVerticalGroup(
            jPanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Ingresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelTransparente_Nuevo.add(jPanelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 210, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Create Account");
        jPanelTransparente_Nuevo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 260, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("User Name :");
        jPanelTransparente_Nuevo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 200, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Password");
        jPanelTransparente_Nuevo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 200, 50));

        jPanelRound5.setColorPrimario(new java.awt.Color(107, 41, 29));
        jPanelRound5.setColorSecundario(new java.awt.Color(134, 124, 112));

        lbl_Ingresar3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lbl_Ingresar3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ingresar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ingresar3.setText("Login");
        lbl_Ingresar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Ingresar3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRound5Layout = new javax.swing.GroupLayout(jPanelRound5);
        jPanelRound5.setLayout(jPanelRound5Layout);
        jPanelRound5Layout.setHorizontalGroup(
            jPanelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Ingresar3, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanelRound5Layout.setVerticalGroup(
            jPanelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Ingresar3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelTransparente_Nuevo.add(jPanelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 210, 40));

        jPanelRound6.setColorPrimario(new java.awt.Color(107, 41, 29));
        jPanelRound6.setColorSecundario(new java.awt.Color(134, 124, 112));

        lbl_Registrar1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lbl_Registrar1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Registrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Registrar1.setText("Return");
        lbl_Registrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Registrar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRound6Layout = new javax.swing.GroupLayout(jPanelRound6);
        jPanelRound6.setLayout(jPanelRound6Layout);
        jPanelRound6Layout.setHorizontalGroup(
            jPanelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound6Layout.createSequentialGroup()
                .addComponent(lbl_Registrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelRound6Layout.setVerticalGroup(
            jPanelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Registrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelTransparente_Nuevo.add(jPanelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        lbl_Cerrar1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbl_Cerrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Cerrar1.setText("X");
        lbl_Cerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Cerrar1MouseClicked(evt);
            }
        });
        jPanelTransparente_Nuevo.add(lbl_Cerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 10, 40, 30));

        jEImagePanel1.add(jPanelTransparente_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 21, 324, 422));

        jPanelTransparente1.setColorPrimario(new java.awt.Color(107, 41, 29));
        jPanelTransparente1.setColorSecundario(new java.awt.Color(134, 124, 112));
        jPanelTransparente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTexfieldPH_FielTex1.setBorder(null);
        jTexfieldPH_FielTex1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexfieldPH_FielTex1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTexfieldPH_FielTex1.setPlaceholder("User Name");
        jPanelTransparente1.add(jTexfieldPH_FielTex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jTexfieldPH_Password1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexfieldPH_Password1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTexfieldPH_Password1.setPlaceholder("Password");
        jPanelTransparente1.add(jTexfieldPH_Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jPanelRound1.setColorPrimario(new java.awt.Color(107, 41, 29));
        jPanelRound1.setColorSecundario(new java.awt.Color(134, 124, 112));

        lbl_Ingresar.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lbl_Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ingresar.setText("Login");
        lbl_Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_IngresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRound1Layout = new javax.swing.GroupLayout(jPanelRound1);
        jPanelRound1.setLayout(jPanelRound1Layout);
        jPanelRound1Layout.setHorizontalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addComponent(lbl_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelRound1Layout.setVerticalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelTransparente1.add(jPanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 210, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login");
        jPanelTransparente1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 200, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("User Name :");
        jPanelTransparente1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 200, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password");
        jPanelTransparente1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 200, 50));

        jPanelRound2.setColorPrimario(new java.awt.Color(107, 41, 29));
        jPanelRound2.setColorSecundario(new java.awt.Color(134, 124, 112));

        lbl_Ingresar1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lbl_Ingresar1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ingresar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ingresar1.setText("Login");
        lbl_Ingresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Ingresar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRound2Layout = new javax.swing.GroupLayout(jPanelRound2);
        jPanelRound2.setLayout(jPanelRound2Layout);
        jPanelRound2Layout.setHorizontalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Ingresar1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanelRound2Layout.setVerticalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Ingresar1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelTransparente1.add(jPanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 210, 40));

        jPanelRound3.setColorPrimario(new java.awt.Color(107, 41, 29));
        jPanelRound3.setColorSecundario(new java.awt.Color(134, 124, 112));

        lbl_Registrar.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lbl_Registrar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Registrar.setText("Sign Up");
        lbl_Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_RegistrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRound3Layout = new javax.swing.GroupLayout(jPanelRound3);
        jPanelRound3.setLayout(jPanelRound3Layout);
        jPanelRound3Layout.setHorizontalGroup(
            jPanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound3Layout.createSequentialGroup()
                .addComponent(lbl_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelRound3Layout.setVerticalGroup(
            jPanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelTransparente1.add(jPanelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        lbl_Cerrar.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbl_Cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Cerrar.setText("X");
        lbl_Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_CerrarMouseClicked(evt);
            }
        });
        jPanelTransparente1.add(lbl_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 10, 40, 30));

        jEImagePanel1.add(jPanelTransparente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 21, 324, 422));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_IngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_IngresarMouseClicked

        String User = jTexfieldPH_FielTex1.getText().trim();
        String Pass = jTexfieldPH_Password1.getText().trim();

        if (jTexfieldPH_FielTex1.getText().isEmpty() || jTexfieldPH_Password1.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, " NO SE PUEDE DEJAR CAMPOS VACIOS");

            jTexfieldPH_FielTex1.setText("");
            jTexfieldPH_Password1.setText("");
        } else {

            try {

                Connection cn = DriverManager.getConnection(Base_de_Datos, Usuario, Clave);

                PreparedStatement pst = cn.prepareStatement("select * from USUARIOS  where NombreUsuario = ?");

                pst.setString(1, jTexfieldPH_FielTex1.getText().trim());
                ResultSet rs = pst.executeQuery();

                PreparedStatement pst2 = cn.prepareStatement("select * from USUARIOS  where Pass = ?");

                pst2.setString(1, jTexfieldPH_Password1.getText().trim());
                ResultSet rs2 = pst2.executeQuery();

                if (rs.next()) {

                    if (rs2.next()) {
                        JOptionPane.showMessageDialog(null, "Bienvenido" + "    " + rs.getString("NombreUsuario"));

                        Principal ventana = new Principal();
                        ventana.setVisible(true);
                        this.dispose();
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "No registrado.");
                    jTexfieldPH_FielTex1.setText("");
                    jTexfieldPH_Password1.setText("");

                }

            } catch (Exception e) {

            }

        }

// TODO add your handling code here:
    }//GEN-LAST:event_lbl_IngresarMouseClicked

    private void lbl_Ingresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Ingresar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Ingresar1MouseClicked

    private void lbl_RegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RegistrarMouseClicked

        jPanelTransparente_Nuevo.setVisible(true);
        jPanelTransparente1.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_RegistrarMouseClicked

    private void lbl_CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CerrarMouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_CerrarMouseClicked

    private void lbl_Ingresar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Ingresar2MouseClicked

        jPanelTransparente_Nuevo.setVisible(true);
        jPanelTransparente1.setVisible(false);

        if (jTexfieldPH_FielTex2.getText().isEmpty()
                || jTexfieldPH_Password2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, " NO PUEDE DEJAR CAMPOS VACIOS ");

            jTexfieldPH_FielTex2.setText("");

            jTexfieldPH_Password2.setText("");

        } else {

            try {
                Connection cn = DriverManager.getConnection(Base_de_Datos, Usuario, Clave);

                PreparedStatement pst = cn.prepareStatement("insert into usuarios values(?,?)");
                //en la variables pst de tipo coneccion a base de datos inserte
                // pst.setString(1, "0");

                pst.setString(1, jTexfieldPH_FielTex2.getText().trim());

                pst.setString(2, jTexfieldPH_Password2.getText().trim());

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, " USUARIO REGISTRADO CORRECTAMENTE");

                jTexfieldPH_FielTex2.setText("");

                jTexfieldPH_Password2.setText("");

            } catch (Exception e) {

            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Ingresar2MouseClicked

    private void lbl_Ingresar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Ingresar3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Ingresar3MouseClicked

    private void lbl_Registrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Registrar1MouseClicked
        jPanelTransparente_Nuevo.setVisible(false);
        jPanelTransparente1.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Registrar1MouseClicked

    private void lbl_Cerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Cerrar1MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Cerrar1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private LIB.JPanelRound jPanelRound1;
    private LIB.JPanelRound jPanelRound2;
    private LIB.JPanelRound jPanelRound3;
    private LIB.JPanelRound jPanelRound4;
    private LIB.JPanelRound jPanelRound5;
    private LIB.JPanelRound jPanelRound6;
    private LIB.JPanelTransparente jPanelTransparente1;
    private LIB.JPanelTransparente jPanelTransparente_Nuevo;
    private LIB.JTexfieldPH_FielTex jTexfieldPH_FielTex1;
    private LIB.JTexfieldPH_FielTex jTexfieldPH_FielTex2;
    private LIB.JTexfieldPH_Password jTexfieldPH_Password1;
    private LIB.JTexfieldPH_Password jTexfieldPH_Password2;
    private javax.swing.JLabel lbl_Cerrar;
    private javax.swing.JLabel lbl_Cerrar1;
    private javax.swing.JLabel lbl_Ingresar;
    private javax.swing.JLabel lbl_Ingresar1;
    private javax.swing.JLabel lbl_Ingresar2;
    private javax.swing.JLabel lbl_Ingresar3;
    private javax.swing.JLabel lbl_Registrar;
    private javax.swing.JLabel lbl_Registrar1;
    // End of variables declaration//GEN-END:variables
}
