/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas_Tablas;
import Finanzas_Clases.Actividad;

/**
 *
 * @author Brayan Cifuentes
 */
public class Actividad_V extends javax.swing.JFrame {

    /**
     * Creates new form Actividad_V
     */
    int x,

    /**
     * Creates new form Actividad_V
     */
    y;
    
    public Actividad_V() {
        initComponents();
        
        txt_id_A.setVisible(false);
        txt_TA.setVisible(false);
        jTextArea_DescripcionA.setVisible(false);
        
        Finanzas_Clases.Actividad AC = new Finanzas_Clases.Actividad(txt_id_A, txt_TA, jTextArea_DescripcionA, txt_BuscarA, tbl_A);
        AC.Actualizar_Tabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_AP = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        Movimiento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_BuscarAP = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_DPI_AP = new javax.swing.JLabel();
        txt_id_A = new javax.swing.JTextField();
        txt_TA = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_DescripcionA = new javax.swing.JTextArea();
        txt_BuscarA = new javax.swing.JTextField();
        jScrollPane35 = new javax.swing.JScrollPane();
        tbl_A = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_AP.setBackground(new java.awt.Color(28, 27, 33));
        Panel_AP.setEnabled(false);
        Panel_AP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Actividad");
        Panel_AP.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 280, 40));

        Movimiento.setBackground(new java.awt.Color(28, 27, 33));
        Movimiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovimientoMouseDragged(evt);
            }
        });
        Movimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovimientoMousePressed(evt);
            }
        });
        Movimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Movimiento.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 20, 30));

        Panel_AP.add(Movimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 40));

        jLabel_BuscarAP.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_BuscarAP.setText("Buscar");
        jLabel_BuscarAP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BuscarAPMouseClicked(evt);
            }
        });
        Panel_AP.add(jLabel_BuscarAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 50, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_D.png"))); // NOI18N
        Panel_AP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel_DPI_AP.setBackground(new java.awt.Color(40, 41, 46));
        jLabel_DPI_AP.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_DPI_AP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Panel_AP.add(jLabel_DPI_AP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 90, 20));

        txt_id_A.setBackground(new java.awt.Color(40, 41, 46));
        txt_id_A.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_A.setBorder(null);
        txt_id_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_AActionPerformed(evt);
            }
        });
        Panel_AP.add(txt_id_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 140, 20));

        txt_TA.setBackground(new java.awt.Color(40, 41, 46));
        txt_TA.setForeground(new java.awt.Color(255, 255, 255));
        txt_TA.setBorder(null);
        txt_TA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TAActionPerformed(evt);
            }
        });
        Panel_AP.add(txt_TA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 140, 20));

        jTextArea_DescripcionA.setBackground(new java.awt.Color(40, 41, 46));
        jTextArea_DescripcionA.setColumns(20);
        jTextArea_DescripcionA.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_DescripcionA.setRows(5);
        jTextArea_DescripcionA.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jScrollPane4.setViewportView(jTextArea_DescripcionA);

        Panel_AP.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 160, 40));

        txt_BuscarA.setBackground(new java.awt.Color(40, 41, 46));
        txt_BuscarA.setForeground(new java.awt.Color(255, 255, 255));
        txt_BuscarA.setBorder(null);
        txt_BuscarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BuscarAActionPerformed(evt);
            }
        });
        txt_BuscarA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarAKeyReleased(evt);
            }
        });
        Panel_AP.add(txt_BuscarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 260, 20));

        tbl_A.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_A.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_A.setSelectionBackground(new java.awt.Color(40, 41, 46));
        tbl_A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_AMouseClicked(evt);
            }
        });
        jScrollPane35.setViewportView(tbl_A);

        Panel_AP.add(jScrollPane35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 600, 190));

        getContentPane().add(Panel_AP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void MovimientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_MovimientoMouseDragged

    private void MovimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_MovimientoMousePressed

    private void jLabel_BuscarAPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BuscarAPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_BuscarAPMouseClicked

    private void txt_id_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_AActionPerformed

    private void txt_TAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TAActionPerformed

    private void txt_BuscarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BuscarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BuscarAActionPerformed

    private void txt_BuscarAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarAKeyReleased
        // TODO add your handling code here:
        Actividad AC = new Actividad(txt_id_A, txt_TA, jTextArea_DescripcionA, txt_BuscarA, tbl_A);
        AC.Buscar_ACF(txt_BuscarA.getText());
    }//GEN-LAST:event_txt_BuscarAKeyReleased

    private void tbl_AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_AMouseClicked
        // TODO add your handling code here:
        int Seleccion = tbl_A.rowAtPoint(evt.getPoint());
        txt_id_A.setText(String.valueOf(tbl_A.getValueAt(Seleccion, 0)));
        txt_TA.setText(String.valueOf(tbl_A.getValueAt(Seleccion, 1)));
        jTextArea_DescripcionA.setText(String.valueOf(tbl_A.getValueAt(Seleccion, 2)));
    }//GEN-LAST:event_tbl_AMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad_V().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Movimiento;
    private javax.swing.JPanel Panel_AP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_BuscarAP;
    private javax.swing.JLabel jLabel_DPI_AP;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea_DescripcionA;
    private javax.swing.JTable tbl_A;
    private javax.swing.JTextField txt_BuscarA;
    private javax.swing.JTextField txt_TA;
    private javax.swing.JTextField txt_id_A;
    // End of variables declaration//GEN-END:variables
}
