/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas_Tablas;

import Finanzas_Clases.Aplicacion;
import static Ventanas_Tablas.Medio_Ve.Item_SE;
import static Ventanas_Tablas.Medio_Ve.S_Emp;

/**
 *
 * @author Langas
 */
public class Aplicacion_V extends javax.swing.JFrame {

    /**
     * Creates new form Aplicacion_V
     */
    
    int x, y;
    
    public static String S_CV = "Curriculum";
    public static String Item_CV = "";
    
    public Aplicacion_V() {
        initComponents();
        
        txt_id_AP.setVisible(false);
        jComboBox_DPIAP.setVisible(false);
        jLabel_DPI_AP.setVisible(false);
        txt_RequisitosAP.setVisible(false);
        
        jComboBox_TablasB_Aplicacion.addItem(S_CV);
        
        Aplicacion ap = new Aplicacion(txt_id_AP, jLabel_DPI_AP, txt_RequisitosAP, txt_BuscarAP, tbl_AP);
        ap.Encontrar_ListaAplicacion("curriculum", "nombres_persona", jComboBox_DPIAP);
        ap.Actualizar_Tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Aplicacion = new javax.swing.JPanel();
        txt_id_AP = new javax.swing.JTextField();
        jComboBox_DPIAP = new javax.swing.JComboBox<>();
        jLabel_DPI_AP = new javax.swing.JLabel();
        txt_RequisitosAP = new javax.swing.JTextField();
        txt_BuscarAP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel_BuscarAP = new javax.swing.JLabel();
        jScrollPane31 = new javax.swing.JScrollPane();
        tbl_AP = new javax.swing.JTable();
        jLabel_Titulo = new javax.swing.JLabel();
        Movimiento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_TablasB_Aplicacion = new javax.swing.JComboBox<>();
        jLabel_Buscar_Tablas_Aplicacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aplicacion.setBackground(new java.awt.Color(28, 27, 33));
        Aplicacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id_AP.setBackground(new java.awt.Color(40, 41, 46));
        txt_id_AP.setForeground(new java.awt.Color(153, 153, 153));
        txt_id_AP.setBorder(null);
        txt_id_AP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_APActionPerformed(evt);
            }
        });
        Aplicacion.add(txt_id_AP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 140, 20));

        jComboBox_DPIAP.setBackground(new java.awt.Color(40, 41, 46));
        jComboBox_DPIAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DPIAPActionPerformed(evt);
            }
        });
        Aplicacion.add(jComboBox_DPIAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 140, -1));

        jLabel_DPI_AP.setBackground(new java.awt.Color(40, 41, 46));
        jLabel_DPI_AP.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_DPI_AP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Aplicacion.add(jLabel_DPI_AP, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 90, 20));

        txt_RequisitosAP.setBackground(new java.awt.Color(40, 41, 46));
        txt_RequisitosAP.setForeground(new java.awt.Color(153, 153, 153));
        txt_RequisitosAP.setBorder(null);
        txt_RequisitosAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RequisitosAPActionPerformed(evt);
            }
        });
        Aplicacion.add(txt_RequisitosAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 140, 20));

        txt_BuscarAP.setBackground(new java.awt.Color(40, 41, 46));
        txt_BuscarAP.setForeground(new java.awt.Color(153, 153, 153));
        txt_BuscarAP.setBorder(null);
        txt_BuscarAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BuscarAPActionPerformed(evt);
            }
        });
        txt_BuscarAP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarAPKeyReleased(evt);
            }
        });
        Aplicacion.add(txt_BuscarAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 240, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_D.png"))); // NOI18N
        Aplicacion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        jLabel_BuscarAP.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_BuscarAP.setText("Buscar");
        jLabel_BuscarAP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BuscarAPMouseClicked(evt);
            }
        });
        Aplicacion.add(jLabel_BuscarAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 50, 20));

        tbl_AP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_AP.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_AP.setSelectionBackground(new java.awt.Color(0, 204, 255));
        tbl_AP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_APMouseClicked(evt);
            }
        });
        jScrollPane31.setViewportView(tbl_AP);

        Aplicacion.add(jScrollPane31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 600, 190));

        jLabel_Titulo.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Aplicacion");
        Aplicacion.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 250, 40));

        Movimiento.setBackground(new java.awt.Color(28, 27, 33));
        Movimiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovimientoMouseDragged(evt);
            }
        });
        Movimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovimientoMousePressed(evt);
            }
        });
        Movimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Movimiento.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 20, 30));

        Aplicacion.add(Movimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 40));

        jComboBox_TablasB_Aplicacion.setBackground(new java.awt.Color(40, 41, 46));
        jComboBox_TablasB_Aplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TablasB_AplicacionActionPerformed(evt);
            }
        });
        Aplicacion.add(jComboBox_TablasB_Aplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 170, -1));

        jLabel_Buscar_Tablas_Aplicacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Buscar_Tablas_Aplicacion.setText("Buscar");
        jLabel_Buscar_Tablas_Aplicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Buscar_Tablas_AplicacionMouseClicked(evt);
            }
        });
        Aplicacion.add(jLabel_Buscar_Tablas_Aplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(813, 320, -1, -1));

        getContentPane().add(Aplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_APActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_APActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_APActionPerformed

    private void jComboBox_DPIAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DPIAPActionPerformed
        // TODO add your handling code here:
        Aplicacion ap = new Aplicacion(txt_id_AP, jLabel_DPI_AP, txt_RequisitosAP, txt_BuscarAP, tbl_AP);
        ap.EncontrarID_dpi("dpi_persona", "curriculum", "nombres_persona", jComboBox_DPIAP, jLabel_DPI_AP);
    }//GEN-LAST:event_jComboBox_DPIAPActionPerformed

    private void txt_RequisitosAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RequisitosAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_RequisitosAPActionPerformed

    private void txt_BuscarAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BuscarAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BuscarAPActionPerformed

    private void txt_BuscarAPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarAPKeyReleased
        // TODO add your handling code here:
        Aplicacion ap = new Aplicacion(txt_id_AP, jLabel_DPI_AP, txt_RequisitosAP, txt_BuscarAP, tbl_AP);
        ap.Buscar_AplicacionE(txt_BuscarAP.getText());
    }//GEN-LAST:event_txt_BuscarAPKeyReleased

    private void jLabel_BuscarAPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BuscarAPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_BuscarAPMouseClicked

    private void tbl_APMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_APMouseClicked
        // TODO add your handling code here:

        int Seleccion = tbl_AP.rowAtPoint(evt.getPoint());

        txt_id_AP.setText(String.valueOf(tbl_AP.getValueAt(Seleccion, 0)));
        jLabel_DPI_AP.setText(String.valueOf(tbl_AP.getValueAt(Seleccion, 1)));
        txt_RequisitosAP.setText(String.valueOf(tbl_AP.getValueAt(Seleccion, 2)));

        Aplicacion ap = new Aplicacion(txt_id_AP, jLabel_DPI_AP, txt_RequisitosAP, txt_BuscarAP, tbl_AP);
        ap.BuscarFila_AP("nombres_persona", "curriculum", "dpi_persona", jComboBox_DPIAP, jLabel_DPI_AP);
    }//GEN-LAST:event_tbl_APMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void MovimientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_MovimientoMouseDragged

    private void MovimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_MovimientoMousePressed

    private void jComboBox_TablasB_AplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TablasB_AplicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TablasB_AplicacionActionPerformed

    private void jLabel_Buscar_Tablas_AplicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Buscar_Tablas_AplicacionMouseClicked
        
        Item_CV = jComboBox_TablasB_Aplicacion.getSelectedItem().toString();
        

        if (Item_CV == S_CV) {
            Curriculum_V CV = new Curriculum_V();
            CV.setVisible(true);
        }
    }//GEN-LAST:event_jLabel_Buscar_Tablas_AplicacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion_V().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Aplicacion;
    private javax.swing.JPanel Movimiento;
    private javax.swing.JComboBox<String> jComboBox_DPIAP;
    private javax.swing.JComboBox<String> jComboBox_TablasB_Aplicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_BuscarAP;
    private javax.swing.JLabel jLabel_Buscar_Tablas_Aplicacion;
    private javax.swing.JLabel jLabel_DPI_AP;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JTable tbl_AP;
    private javax.swing.JTextField txt_BuscarAP;
    private javax.swing.JTextField txt_RequisitosAP;
    private javax.swing.JTextField txt_id_AP;
    // End of variables declaration//GEN-END:variables
}
