/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas_Tablas;

import static Finanzas.Principal.Item_Contratacion;
import static Finanzas.Principal.Item_D;
import static Finanzas.Principal.Item_P;
import static Finanzas.Principal.S_Contratacion;
import static Finanzas.Principal.S_Departamento;
import static Finanzas.Principal.S_Puesto;
import Finanzas_Clases.Contratacion;

/**
 *
 * @author Brayan Cifuentes
 */
public class Contratacion_V extends javax.swing.JFrame {

    /**
     * Creates new form Contratacion_V
     */
    
    int x, y;
    public static String S_PeriodoP = "Periodo Prueba";
    public static String Item_Periodop = "";
    
    public Contratacion_V() {
        initComponents();
        
        jComboBox_Aplicacion.addItem(S_PeriodoP);
        
        Contratacion C = new Contratacion(txt_id_C, jLabel_PPCC, txt_FC, txt_DC, txt_EC, txt_Buscar_C, tbl_C);
        C.Actualizar_Tabla();
        
        txt_id_C.setVisible(false);
        jComboBox_PPC.setVisible(false);
        jLabel_PPCC.setVisible(false);
        txt_FC.setVisible(false);
        txt_DC.setVisible(false);
        txt_EC.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_AP = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        Movimiento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_BuscarAP = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane37 = new javax.swing.JScrollPane();
        tbl_C = new javax.swing.JTable();
        txt_Buscar_C = new javax.swing.JTextField();
        txt_DC = new javax.swing.JTextField();
        txt_EC = new javax.swing.JTextField();
        txt_id_C = new javax.swing.JTextField();
        jComboBox_PPC = new javax.swing.JComboBox<>();
        jLabel_PPCC = new javax.swing.JLabel();
        txt_FC = new javax.swing.JTextField();
        jComboBox_Aplicacion = new javax.swing.JComboBox<>();
        jLabel_Buscar_TablasEC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Panel_AP.setBackground(new java.awt.Color(28, 27, 33));
        Panel_AP.setEnabled(false);
        Panel_AP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Contratación");
        Panel_AP.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 280, 40));

        Movimiento.setBackground(new java.awt.Color(28, 27, 33));
        Movimiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovimientoMouseDragged(evt);
            }
        });
        Movimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovimientoMousePressed(evt);
            }
        });
        Movimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Movimiento.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 20, 30));

        Panel_AP.add(Movimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 40));

        jLabel_BuscarAP.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_BuscarAP.setText("Buscar");
        jLabel_BuscarAP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BuscarAPMouseClicked(evt);
            }
        });
        Panel_AP.add(jLabel_BuscarAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 50, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_D.png"))); // NOI18N
        Panel_AP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        tbl_C.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_C.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_C.setSelectionBackground(new java.awt.Color(0, 204, 255));
        tbl_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_CMouseClicked(evt);
            }
        });
        jScrollPane37.setViewportView(tbl_C);

        Panel_AP.add(jScrollPane37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 600, 190));

        txt_Buscar_C.setBackground(new java.awt.Color(40, 41, 46));
        txt_Buscar_C.setForeground(new java.awt.Color(153, 153, 153));
        txt_Buscar_C.setBorder(null);
        txt_Buscar_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Buscar_CActionPerformed(evt);
            }
        });
        txt_Buscar_C.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Buscar_CKeyReleased(evt);
            }
        });
        Panel_AP.add(txt_Buscar_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 290, 20));

        txt_DC.setBackground(new java.awt.Color(40, 41, 46));
        txt_DC.setForeground(new java.awt.Color(153, 153, 153));
        txt_DC.setBorder(null);
        txt_DC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DCActionPerformed(evt);
            }
        });
        Panel_AP.add(txt_DC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 140, 20));

        txt_EC.setBackground(new java.awt.Color(40, 41, 46));
        txt_EC.setForeground(new java.awt.Color(153, 153, 153));
        txt_EC.setBorder(null);
        txt_EC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ECActionPerformed(evt);
            }
        });
        Panel_AP.add(txt_EC, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 140, 20));

        txt_id_C.setBackground(new java.awt.Color(40, 41, 46));
        txt_id_C.setForeground(new java.awt.Color(153, 153, 153));
        txt_id_C.setBorder(null);
        txt_id_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_CActionPerformed(evt);
            }
        });
        Panel_AP.add(txt_id_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 140, 20));

        jComboBox_PPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_PPCActionPerformed(evt);
            }
        });
        jComboBox_PPC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox_PPCKeyReleased(evt);
            }
        });
        Panel_AP.add(jComboBox_PPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 140, -1));

        jLabel_PPCC.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PPCC.setText("1");
        Panel_AP.add(jLabel_PPCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 30, 20));

        txt_FC.setBackground(new java.awt.Color(40, 41, 46));
        txt_FC.setForeground(new java.awt.Color(153, 153, 153));
        txt_FC.setBorder(null);
        txt_FC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FCActionPerformed(evt);
            }
        });
        Panel_AP.add(txt_FC, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 140, 20));

        jComboBox_Aplicacion.setBackground(new java.awt.Color(40, 41, 46));
        jComboBox_Aplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_AplicacionActionPerformed(evt);
            }
        });
        Panel_AP.add(jComboBox_Aplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 170, -1));

        jLabel_Buscar_TablasEC.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Buscar_TablasEC.setText("Buscar");
        jLabel_Buscar_TablasEC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Buscar_TablasECMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Buscar_TablasECMouseEntered(evt);
            }
        });
        Panel_AP.add(jLabel_Buscar_TablasEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_AP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_AP, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void MovimientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_MovimientoMouseDragged

    private void MovimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_MovimientoMousePressed

    private void jLabel_BuscarAPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BuscarAPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_BuscarAPMouseClicked

    private void tbl_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_CMouseClicked
        int Seleccion = tbl_C.rowAtPoint(evt.getPoint());
        txt_id_C.setText(String.valueOf(tbl_C.getValueAt(Seleccion, 0)));
        jLabel_PPCC.setText(String.valueOf(tbl_C.getValueAt(Seleccion, 1)));
        txt_FC.setText(String.valueOf(tbl_C.getValueAt(Seleccion, 2)));
        txt_DC.setText(String.valueOf(tbl_C.getValueAt(Seleccion, 3)));
        txt_EC.setText(String.valueOf(tbl_C.getValueAt(Seleccion, 4)));
        Contratacion C = new Contratacion(txt_id_C, jLabel_PPCC, txt_FC, txt_DC, txt_EC, txt_Buscar_C, tbl_C);
        C.BuscarFila_Contratacion("id_periodop", "periodo_prueba", "id_periodop", jComboBox_PPC, jLabel_PPCC);

        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_CMouseClicked

    private void txt_Buscar_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Buscar_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Buscar_CActionPerformed

    private void txt_Buscar_CKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Buscar_CKeyReleased
        Contratacion C = new Contratacion(txt_id_C, jLabel_PPCC, txt_FC, txt_DC, txt_EC, txt_Buscar_C, tbl_C);
        C.Buscar_SolicitudCon(txt_Buscar_C.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Buscar_CKeyReleased

    private void txt_DCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DCActionPerformed

    private void txt_ECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ECActionPerformed

    private void txt_id_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_CActionPerformed

    private void jComboBox_PPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_PPCActionPerformed
        Contratacion C = new Contratacion(txt_id_C, jLabel_PPCC, txt_FC, txt_DC, txt_EC, txt_Buscar_C, tbl_C);
        C.EncontrarID_Contratacion("id_periodop", "periodo_prueba", "id_periodop", jComboBox_PPC, jLabel_PPCC);
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_PPCActionPerformed

    private void jComboBox_PPCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_PPCKeyReleased

        Contratacion C = new Contratacion(txt_id_C, jLabel_PPCC, txt_FC, txt_DC, txt_EC, txt_Buscar_C, tbl_C);
        C.Buscar_Contratacion(txt_Buscar_C.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_PPCKeyReleased

    private void txt_FCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FCActionPerformed

    private void jComboBox_AplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_AplicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_AplicacionActionPerformed

    private void jLabel_Buscar_TablasECMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Buscar_TablasECMouseClicked
        // TODO add your handling code here:
        Item_Periodop = jComboBox_Aplicacion.getSelectedItem().toString();

        if (Item_Periodop == S_PeriodoP) {
            Periodo_Prueba_V pp = new Periodo_Prueba_V();
            pp.setVisible(true);
        }

    }//GEN-LAST:event_jLabel_Buscar_TablasECMouseClicked

    private void jLabel_Buscar_TablasECMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Buscar_TablasECMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Buscar_TablasECMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contratacion_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contratacion_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contratacion_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contratacion_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contratacion_V().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Movimiento;
    private javax.swing.JPanel Panel_AP;
    private javax.swing.JComboBox<String> jComboBox_Aplicacion;
    private javax.swing.JComboBox<String> jComboBox_PPC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_BuscarAP;
    private javax.swing.JLabel jLabel_Buscar_TablasEC;
    private javax.swing.JLabel jLabel_PPCC;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JTable tbl_C;
    private javax.swing.JTextField txt_Buscar_C;
    private javax.swing.JTextField txt_DC;
    private javax.swing.JTextField txt_EC;
    private javax.swing.JTextField txt_FC;
    private javax.swing.JTextField txt_id_C;
    // End of variables declaration//GEN-END:variables
}
