/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas_Tablas;

import Clases_RRHH.Departamento;
import Clases_RRHH.Experiencia_Laboral_Detallada;
import Clases_RRHH.Puesto;
import Clases_RRHH.Departamento;

/**
 *
 * @author Langas
 */
public class Departamento_V extends javax.swing.JFrame {

    /**
     * Creates new form ExpLD
     */
    int x, y;

    public Departamento_V() {
        initComponents();

        //AWTUtilities.setWindowOpacity();
       Departamento De = new Departamento(txt_id_Departamento.toString(), txt_Nombre_Departamento.toString(), txt_Estatus_Departamento.toString());
       De.Actualizar_Tabla(tbl_Departamento);
       

        txt_id_Departamento.setVisible(false);
        txt_Buscar.setVisible(false);
        txt_Estatus_Departamento.setVisible(false);
        txt_Nombre_Departamento.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExpLD = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        Movimiento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_id_Departamento = new javax.swing.JTextField();
        txt_Nombre_Departamento = new javax.swing.JTextField();
        txt_Estatus_Departamento = new javax.swing.JTextField();
        txt_Buscar = new javax.swing.JTextField();
        txt_Buscar1 = new javax.swing.JTextField();
        jLabel_Buscar = new javax.swing.JLabel();
        icono_Buscar = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        tbl_Departamento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExpLD.setBackground(new java.awt.Color(28, 27, 33));
        ExpLD.setEnabled(false);
        ExpLD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Departamento");
        ExpLD.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 280, 40));

        Movimiento.setBackground(new java.awt.Color(28, 27, 33));
        Movimiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovimientoMouseDragged(evt);
            }
        });
        Movimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovimientoMousePressed(evt);
            }
        });
        Movimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Movimiento.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 20, 30));

        ExpLD.add(Movimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 40));

        txt_id_Departamento.setBackground(new java.awt.Color(231, 231, 231));
        txt_id_Departamento.setForeground(new java.awt.Color(153, 153, 153));
        txt_id_Departamento.setBorder(null);
        txt_id_Departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_DepartamentoActionPerformed(evt);
            }
        });
        ExpLD.add(txt_id_Departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 140, 20));

        txt_Nombre_Departamento.setBackground(new java.awt.Color(231, 231, 231));
        txt_Nombre_Departamento.setForeground(new java.awt.Color(153, 153, 153));
        txt_Nombre_Departamento.setBorder(null);
        txt_Nombre_Departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nombre_DepartamentoActionPerformed(evt);
            }
        });
        ExpLD.add(txt_Nombre_Departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 150, 20));

        txt_Estatus_Departamento.setBackground(new java.awt.Color(231, 231, 231));
        txt_Estatus_Departamento.setForeground(new java.awt.Color(153, 153, 153));
        txt_Estatus_Departamento.setBorder(null);
        txt_Estatus_Departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Estatus_DepartamentoActionPerformed(evt);
            }
        });
        ExpLD.add(txt_Estatus_Departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 140, 20));

        txt_Buscar.setBackground(new java.awt.Color(231, 231, 231));
        txt_Buscar.setForeground(new java.awt.Color(153, 153, 153));
        txt_Buscar.setBorder(null);
        txt_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BuscarActionPerformed(evt);
            }
        });
        txt_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarKeyReleased(evt);
            }
        });
        ExpLD.add(txt_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 240, 20));

        txt_Buscar1.setBackground(new java.awt.Color(40, 41, 46));
        txt_Buscar1.setForeground(new java.awt.Color(255, 255, 255));
        txt_Buscar1.setBorder(null);
        txt_Buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Buscar1ActionPerformed(evt);
            }
        });
        txt_Buscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Buscar1KeyReleased(evt);
            }
        });
        ExpLD.add(txt_Buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 240, 20));

        jLabel_Buscar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Buscar.setText("Buscar");
        ExpLD.add(jLabel_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 50, 20));

        icono_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_D.png"))); // NOI18N
        ExpLD.add(icono_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 20, 20));

        jScrollPane21.setBackground(new java.awt.Color(40, 41, 46));

        tbl_Departamento.setBackground(new java.awt.Color(40, 41, 46));
        tbl_Departamento.setForeground(new java.awt.Color(255, 255, 255));
        tbl_Departamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_Departamento.setToolTipText("");
        tbl_Departamento.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_Departamento.setSelectionBackground(new java.awt.Color(40, 41, 46));
        tbl_Departamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DepartamentoMouseClicked(evt);
            }
        });
        jScrollPane21.setViewportView(tbl_Departamento);

        ExpLD.add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 600, 190));

        getContentPane().add(ExpLD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 440));

        setBounds(0, 0, 680, 439);
    }// </editor-fold>//GEN-END:initComponents

    private void MovimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_MovimientoMousePressed

    private void MovimientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_MovimientoMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txt_id_DepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_DepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_DepartamentoActionPerformed

    private void txt_Nombre_DepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nombre_DepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nombre_DepartamentoActionPerformed

    private void txt_Estatus_DepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Estatus_DepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Estatus_DepartamentoActionPerformed

    private void txt_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BuscarActionPerformed

    private void txt_BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarKeyReleased
        // TODO add your handling code here:
       Departamento De = new Departamento(txt_id_Departamento.toString(), txt_Nombre_Departamento.toString(), txt_Estatus_Departamento.toString());
        De.Buscar_Departamento(txt_Buscar.getText(), tbl_Departamento);
    }//GEN-LAST:event_txt_BuscarKeyReleased

    private void txt_Buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Buscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Buscar1ActionPerformed

    private void txt_Buscar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Buscar1KeyReleased
        // TODO add your handling code here:
       Departamento De = new Departamento(txt_id_Departamento.toString(), txt_Nombre_Departamento.toString(), txt_Estatus_Departamento.toString());
        De.Buscar_Departamento(txt_Buscar.getText(), tbl_Departamento);
    }//GEN-LAST:event_txt_Buscar1KeyReleased

    private void tbl_DepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DepartamentoMouseClicked
        // TODO add your handling code here:
        int Seleccion = tbl_Departamento.rowAtPoint(evt.getPoint());
        txt_id_Departamento.setText(String.valueOf(tbl_Departamento.getValueAt(Seleccion, 0)));
        txt_Nombre_Departamento.setText(String.valueOf(tbl_Departamento.getValueAt(Seleccion, 1)));
        txt_Estatus_Departamento.setText(String.valueOf(tbl_Departamento.getValueAt(Seleccion, 2)));
    }//GEN-LAST:event_tbl_DepartamentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Departamento_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Departamento_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Departamento_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Departamento_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Departamento_V().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ExpLD;
    private javax.swing.JPanel Movimiento;
    private javax.swing.JLabel icono_Buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Buscar;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JTable tbl_Departamento;
    private javax.swing.JTextField txt_Buscar;
    private javax.swing.JTextField txt_Buscar1;
    private javax.swing.JTextField txt_Estatus_Departamento;
    private javax.swing.JTextField txt_Nombre_Departamento;
    private javax.swing.JTextField txt_id_Departamento;
    // End of variables declaration//GEN-END:variables
}
