/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas_Tablas;

import static Finanzas.Principal.Item_SE;
import Finanzas_Clases.Medio;
import Finanzas_Clases.Puesto;

/**
 *
 * @author jorgi
 */
public class Medio_Ve extends javax.swing.JFrame {

    /**
     * Creates new form Medio_Ve
     */
    int x;
    int y;
    public static String S_Emp = "Solicitud Empresarial";
    public static String Item_SE = "";
    public Medio_Ve() {
        initComponents();
        
        jComboBox_TablasB_SE1.addItem(S_Emp);
        
        Medio M = new Medio(txt_id_Medio, jLabel_ID_SEM, txt_NombreM, jTextArea_DescripcionM, txt_BuscarM, tbl_Medio);
        M.Actualizar_Tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExpLD = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        Movimiento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_id_Medio = new javax.swing.JTextField();
        jComboBox_IDSEM = new javax.swing.JComboBox<>();
        jLabel_ID_SEM = new javax.swing.JLabel();
        txt_NombreM = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_DescripcionM = new javax.swing.JTextArea();
        txt_BuscarM = new javax.swing.JTextField();
        jScrollPane27 = new javax.swing.JScrollPane();
        tbl_Medio = new javax.swing.JTable();
        jLabel_BuscarM = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_TablasB_SE1 = new javax.swing.JComboBox<>();
        jLabel_Buscar_Tablas_M1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ExpLD.setBackground(new java.awt.Color(28, 27, 33));
        ExpLD.setEnabled(false);
        ExpLD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Medio.");
        ExpLD.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 280, 40));

        Movimiento.setBackground(new java.awt.Color(28, 27, 33));
        Movimiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovimientoMouseDragged(evt);
            }
        });
        Movimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovimientoMousePressed(evt);
            }
        });
        Movimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Movimiento.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 20, 30));

        ExpLD.add(Movimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 40));

        txt_id_Medio.setBackground(new java.awt.Color(40, 41, 46));
        txt_id_Medio.setBorder(null);
        txt_id_Medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_MedioActionPerformed(evt);
            }
        });
        ExpLD.add(txt_id_Medio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 140, 20));

        jComboBox_IDSEM.setBackground(new java.awt.Color(40, 41, 46));
        jComboBox_IDSEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_IDSEMActionPerformed(evt);
            }
        });
        ExpLD.add(jComboBox_IDSEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 140, 20));

        jLabel_ID_SEM.setForeground(new java.awt.Color(255, 255, 255));
        ExpLD.add(jLabel_ID_SEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 30, 20));

        txt_NombreM.setBackground(new java.awt.Color(40, 41, 46));
        txt_NombreM.setBorder(null);
        txt_NombreM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreMActionPerformed(evt);
            }
        });
        ExpLD.add(txt_NombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 140, 20));

        jTextArea_DescripcionM.setBackground(new java.awt.Color(40, 41, 46));
        jTextArea_DescripcionM.setColumns(20);
        jTextArea_DescripcionM.setRows(5);
        jTextArea_DescripcionM.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setViewportView(jTextArea_DescripcionM);

        ExpLD.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 610, -1, -1));

        txt_BuscarM.setBackground(new java.awt.Color(40, 41, 46));
        txt_BuscarM.setBorder(null);
        txt_BuscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BuscarMActionPerformed(evt);
            }
        });
        txt_BuscarM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarMKeyReleased(evt);
            }
        });
        ExpLD.add(txt_BuscarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 240, 20));

        tbl_Medio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_Medio.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_Medio.setSelectionBackground(new java.awt.Color(0, 204, 255));
        jScrollPane27.setViewportView(tbl_Medio);

        ExpLD.add(jScrollPane27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 600, 190));

        jLabel_BuscarM.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_BuscarM.setText("Buscar");
        jLabel_BuscarM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BuscarMMouseClicked(evt);
            }
        });
        ExpLD.add(jLabel_BuscarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 40, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_D.png"))); // NOI18N
        ExpLD.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jComboBox_TablasB_SE1.setBackground(new java.awt.Color(40, 41, 46));
        jComboBox_TablasB_SE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TablasB_SE1ActionPerformed(evt);
            }
        });
        ExpLD.add(jComboBox_TablasB_SE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 170, -1));

        jLabel_Buscar_Tablas_M1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Buscar_Tablas_M1.setText("Buscar");
        jLabel_Buscar_Tablas_M1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Buscar_Tablas_M1MouseClicked(evt);
            }
        });
        ExpLD.add(jLabel_Buscar_Tablas_M1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ExpLD, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExpLD, javax.swing.GroupLayout.PREFERRED_SIZE, 355, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void MovimientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_MovimientoMouseDragged

    private void MovimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_MovimientoMousePressed

    private void txt_id_MedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_MedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_MedioActionPerformed

    private void jComboBox_IDSEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_IDSEMActionPerformed
        // TODO add your handling code here:
        Medio M = new Medio(txt_id_Medio, jLabel_ID_SEM, txt_NombreM, jTextArea_DescripcionM, txt_BuscarM, tbl_Medio);
        M.EncontrarID_M("id_solicitud", "solicitud_empresarial", "id_solicitud", jComboBox_IDSEM, jLabel_ID_SEM);
    }//GEN-LAST:event_jComboBox_IDSEMActionPerformed

    private void txt_NombreMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreMActionPerformed

    private void txt_BuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BuscarMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BuscarMActionPerformed

    private void txt_BuscarMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarMKeyReleased
        // TODO add your handling code here:
        Medio M = new Medio(txt_id_Medio, jLabel_ID_SEM, txt_NombreM, jTextArea_DescripcionM, txt_BuscarM, tbl_Medio);
        M.Buscar_SolicitudM(txt_BuscarM.getText());
    }//GEN-LAST:event_txt_BuscarMKeyReleased

    private void jLabel_BuscarMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BuscarMMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_BuscarMMouseClicked

    private void jComboBox_TablasB_SE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TablasB_SE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TablasB_SE1ActionPerformed

    private void jLabel_Buscar_Tablas_M1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Buscar_Tablas_M1MouseClicked
        // TODO add your handling code here:
        Item_SE = jComboBox_TablasB_SE1.getSelectedItem().toString();
        //puesto,dep,nive

        if (Item_SE == S_Emp) {
            Solicitud_Empresarial_V MedV = new Solicitud_Empresarial_V();
            MedV.setVisible(true);
        }

    }//GEN-LAST:event_jLabel_Buscar_Tablas_M1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medio_Ve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medio_Ve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medio_Ve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medio_Ve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medio_Ve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ExpLD;
    private javax.swing.JPanel Movimiento;
    private javax.swing.JComboBox<String> jComboBox_IDSEM;
    private javax.swing.JComboBox<String> jComboBox_TablasB_SE1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_BuscarM;
    private javax.swing.JLabel jLabel_Buscar_Tablas_M1;
    private javax.swing.JLabel jLabel_ID_SEM;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea_DescripcionM;
    private javax.swing.JTable tbl_Medio;
    private javax.swing.JTextField txt_BuscarM;
    private javax.swing.JTextField txt_NombreM;
    private javax.swing.JTextField txt_id_Medio;
    // End of variables declaration//GEN-END:variables
}
