/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas_Tablas;

import Finanzas_Clases.Referencias_Personales;

/**
 *
 * @author jorgi
 */
public class Referencias_Personales_V extends javax.swing.JFrame {

    /**
     * Creates new form Referencias_Personales_V
     */
    int x;
    int y;
    public Referencias_Personales_V() {
        initComponents();
        txt_id_RP.setVisible(false);
        txt_Nombre_RP.setVisible(false);
        txt_Telefono_RP.setVisible(false);
        
        Referencias_Personales RP = new Referencias_Personales(txt_id_RP, txt_Nombre_RP, txt_Telefono_RP, txt_Buscar_RP, tbl_RP);
        RP.Actualizar_Tabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExpLD = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        Movimiento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_id_RP = new javax.swing.JTextField();
        txt_Nombre_RP = new javax.swing.JTextField();
        txt_Telefono_RP = new javax.swing.JTextField();
        txt_Buscar_RP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Buscar_RP = new javax.swing.JLabel();
        jScrollPane29 = new javax.swing.JScrollPane();
        tbl_RP = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ExpLD.setBackground(new java.awt.Color(28, 27, 33));
        ExpLD.setEnabled(false);
        ExpLD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Referencias Personales.");
        ExpLD.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 280, 40));

        Movimiento.setBackground(new java.awt.Color(28, 27, 33));
        Movimiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovimientoMouseDragged(evt);
            }
        });
        Movimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovimientoMousePressed(evt);
            }
        });
        Movimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Movimiento.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 20, 30));

        ExpLD.add(Movimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 40));

        txt_id_RP.setBackground(new java.awt.Color(40, 41, 46));
        txt_id_RP.setForeground(new java.awt.Color(153, 153, 153));
        txt_id_RP.setBorder(null);
        txt_id_RP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_RPActionPerformed(evt);
            }
        });
        ExpLD.add(txt_id_RP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 140, 20));

        txt_Nombre_RP.setBackground(new java.awt.Color(40, 41, 46));
        txt_Nombre_RP.setForeground(new java.awt.Color(153, 153, 153));
        txt_Nombre_RP.setBorder(null);
        txt_Nombre_RP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nombre_RPActionPerformed(evt);
            }
        });
        ExpLD.add(txt_Nombre_RP, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 220, 20));

        txt_Telefono_RP.setBackground(new java.awt.Color(40, 41, 46));
        txt_Telefono_RP.setForeground(new java.awt.Color(153, 153, 153));
        txt_Telefono_RP.setBorder(null);
        txt_Telefono_RP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Telefono_RPActionPerformed(evt);
            }
        });
        ExpLD.add(txt_Telefono_RP, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 170, 20));

        txt_Buscar_RP.setBackground(new java.awt.Color(40, 41, 46));
        txt_Buscar_RP.setForeground(new java.awt.Color(153, 153, 153));
        txt_Buscar_RP.setBorder(null);
        txt_Buscar_RP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Buscar_RPActionPerformed(evt);
            }
        });
        txt_Buscar_RP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Buscar_RPKeyReleased(evt);
            }
        });
        ExpLD.add(txt_Buscar_RP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 290, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_D.png"))); // NOI18N
        ExpLD.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jLabel_Buscar_RP.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Buscar_RP.setText("Buscar");
        ExpLD.add(jLabel_Buscar_RP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        tbl_RP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_RP.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_RP.setSelectionBackground(new java.awt.Color(0, 204, 255));
        jScrollPane29.setViewportView(tbl_RP);

        ExpLD.add(jScrollPane29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 600, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExpLD, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExpLD, javax.swing.GroupLayout.PREFERRED_SIZE, 357, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void MovimientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_MovimientoMouseDragged

    private void MovimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_MovimientoMousePressed

    private void txt_id_RPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_RPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_RPActionPerformed

    private void txt_Nombre_RPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nombre_RPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nombre_RPActionPerformed

    private void txt_Telefono_RPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Telefono_RPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Telefono_RPActionPerformed

    private void txt_Buscar_RPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Buscar_RPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Buscar_RPActionPerformed

    private void txt_Buscar_RPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Buscar_RPKeyReleased
        // TODO add your handling code here:
        Referencias_Personales RP = new Referencias_Personales(txt_id_RP, txt_Nombre_RP, txt_Telefono_RP, txt_Buscar_RP, tbl_RP);
        RP.Buscar_ReferenciasP(txt_Buscar_RP.getText());
    }//GEN-LAST:event_txt_Buscar_RPKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Referencias_Personales_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Referencias_Personales_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Referencias_Personales_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Referencias_Personales_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Referencias_Personales_V().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ExpLD;
    private javax.swing.JPanel Movimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Buscar_RP;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JTable tbl_RP;
    private javax.swing.JTextField txt_Buscar_RP;
    private javax.swing.JTextField txt_Nombre_RP;
    private javax.swing.JTextField txt_Telefono_RP;
    private javax.swing.JTextField txt_id_RP;
    // End of variables declaration//GEN-END:variables
}
