/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas_Tablas;

import static Finanzas.Principal.Item_Actividad;
import static Finanzas.Principal.Item_Periodop;
import static Finanzas.Principal.S_Actividad;
import static Finanzas.Principal.S_PeriodoP;
import Finanzas_Clases.Periodo_Prueba;
import Finanzas_Clases.Seleccion;

/**
 *
 * @author Brayan Cifuentes
 */
public class Seleccion_V extends javax.swing.JFrame {

    /**
     * Creates new form Seleccion_V
     */
    int x, y;
    
    public static String S_Aplicacion = "Aplicacion";
    public static String Item_Aplicacion = "";
    
    public Seleccion_V() {
        initComponents();
        
        Seleccion S = new Seleccion(txt_idS, jLabel_RL_APPS, txt_EstatusS, txt_BuscarS, tbl_S);
        S.Actualizar_Tabla();
        
        jComboBox_Seleccion.addItem(S_Aplicacion);
        
        txt_idS.setVisible(false);
        jComboBox_APPS.setVisible(false);
        jLabel_RL_APPS.setVisible(false);
        txt_EstatusS.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_AP = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        Movimiento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_BuscarAP = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane34 = new javax.swing.JScrollPane();
        tbl_S = new javax.swing.JTable();
        txt_idS = new javax.swing.JTextField();
        jComboBox_APPS = new javax.swing.JComboBox<>();
        jLabel_RL_APPS = new javax.swing.JLabel();
        txt_EstatusS = new javax.swing.JTextField();
        txt_BuscarS = new javax.swing.JTextField();
        jComboBox_Seleccion = new javax.swing.JComboBox<>();
        jLabel_Buscar_TablasPP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(28, 27, 33));
        setUndecorated(true);

        Panel_AP.setBackground(new java.awt.Color(28, 27, 33));
        Panel_AP.setEnabled(false);
        Panel_AP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Selección");
        Panel_AP.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 280, 40));

        Movimiento.setBackground(new java.awt.Color(28, 27, 33));
        Movimiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovimientoMouseDragged(evt);
            }
        });
        Movimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovimientoMousePressed(evt);
            }
        });
        Movimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Movimiento.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 20, 30));

        Panel_AP.add(Movimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 730, 40));

        jLabel_BuscarAP.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_BuscarAP.setText("Buscar");
        jLabel_BuscarAP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BuscarAPMouseClicked(evt);
            }
        });
        Panel_AP.add(jLabel_BuscarAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 50, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_D.png"))); // NOI18N
        Panel_AP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        tbl_S.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_S.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_S.setSelectionBackground(new java.awt.Color(0, 204, 255));
        tbl_S.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SMouseClicked(evt);
            }
        });
        jScrollPane34.setViewportView(tbl_S);

        Panel_AP.add(jScrollPane34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 600, 190));

        txt_idS.setBackground(new java.awt.Color(40, 41, 46));
        txt_idS.setForeground(new java.awt.Color(153, 153, 153));
        txt_idS.setBorder(null);
        txt_idS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idSActionPerformed(evt);
            }
        });
        Panel_AP.add(txt_idS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 140, 20));

        jComboBox_APPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_APPSActionPerformed(evt);
            }
        });
        Panel_AP.add(jComboBox_APPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 140, -1));

        jLabel_RL_APPS.setForeground(new java.awt.Color(255, 255, 255));
        Panel_AP.add(jLabel_RL_APPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 30, 20));

        txt_EstatusS.setBackground(new java.awt.Color(40, 41, 46));
        txt_EstatusS.setForeground(new java.awt.Color(153, 153, 153));
        txt_EstatusS.setBorder(null);
        txt_EstatusS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EstatusSActionPerformed(evt);
            }
        });
        Panel_AP.add(txt_EstatusS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 140, 20));

        txt_BuscarS.setBackground(new java.awt.Color(40, 41, 46));
        txt_BuscarS.setForeground(new java.awt.Color(153, 153, 153));
        txt_BuscarS.setBorder(null);
        txt_BuscarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_BuscarSMouseClicked(evt);
            }
        });
        txt_BuscarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BuscarSActionPerformed(evt);
            }
        });
        txt_BuscarS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarSKeyReleased(evt);
            }
        });
        Panel_AP.add(txt_BuscarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 240, 20));

        jComboBox_Seleccion.setBackground(new java.awt.Color(40, 41, 46));
        jComboBox_Seleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_SeleccionActionPerformed(evt);
            }
        });
        Panel_AP.add(jComboBox_Seleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 170, -1));

        jLabel_Buscar_TablasPP.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Buscar_TablasPP.setText("Buscar");
        jLabel_Buscar_TablasPP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Buscar_TablasPPMouseClicked(evt);
            }
        });
        Panel_AP.add(jLabel_Buscar_TablasPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_AP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_AP, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_BuscarAPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BuscarAPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_BuscarAPMouseClicked

    private void MovimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_MovimientoMousePressed

    private void MovimientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_MovimientoMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tbl_SMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SMouseClicked

        int Seleccion = tbl_S.rowAtPoint(evt.getPoint());
        txt_idS.setText(String.valueOf(tbl_S.getValueAt(Seleccion, 0)));
        jLabel_RL_APPS.setText(String.valueOf(tbl_S.getValueAt(Seleccion, 1)));
        txt_EstatusS.setText(String.valueOf(tbl_S.getValueAt(Seleccion, 2)));
        Seleccion S = new Seleccion(txt_idS, jLabel_RL_APPS, txt_EstatusS, txt_BuscarS, tbl_S);
        S.BuscarFila_Seleccion("id_ap", " aplicacion_prueba", " id_ap", jComboBox_APPS, jLabel_RL_APPS);

        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_SMouseClicked

    private void txt_idSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idSActionPerformed

    private void jComboBox_APPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_APPSActionPerformed

        Seleccion S = new Seleccion(txt_idS, jLabel_RL_APPS, txt_EstatusS, txt_BuscarS, tbl_S);
        S.EncontrarID_Seleccion("id_ap", "aplicacion_prueba", "id_ap", jComboBox_APPS, jLabel_RL_APPS);

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_APPSActionPerformed

    private void txt_EstatusSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EstatusSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EstatusSActionPerformed

    private void txt_BuscarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_BuscarSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BuscarSMouseClicked

    private void txt_BuscarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BuscarSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BuscarSActionPerformed

    private void txt_BuscarSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarSKeyReleased

        Seleccion S = new Seleccion(txt_idS, jLabel_RL_APPS, txt_EstatusS, txt_BuscarS, tbl_S);
        S.Buscar_Sele(txt_BuscarS.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BuscarSKeyReleased

    private void jComboBox_SeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_SeleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_SeleccionActionPerformed

    private void jLabel_Buscar_TablasPPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Buscar_TablasPPMouseClicked
        // TODO add your handling code here:

        Item_Aplicacion = jComboBox_Seleccion.getSelectedItem().toString();

        if (Item_Aplicacion == S_Aplicacion) {
            Aplicacion_V ap = new Aplicacion_V();
            ap.setVisible(true);
        }

    }//GEN-LAST:event_jLabel_Buscar_TablasPPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccion_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccion_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccion_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccion_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccion_V().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Movimiento;
    private javax.swing.JPanel Panel_AP;
    private javax.swing.JComboBox<String> jComboBox_APPS;
    private javax.swing.JComboBox<String> jComboBox_Seleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_BuscarAP;
    private javax.swing.JLabel jLabel_Buscar_TablasPP;
    private javax.swing.JLabel jLabel_RL_APPS;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JTable tbl_S;
    private javax.swing.JTextField txt_BuscarS;
    private javax.swing.JTextField txt_EstatusS;
    private javax.swing.JTextField txt_idS;
    // End of variables declaration//GEN-END:variables
}
