/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas_Tablas;

import Finanzas_Clases.Tipo_Prueba;

/**
 *
 * @author Langas
 */
public class TipoPrueba_V extends javax.swing.JFrame {

    /**
     * Creates new form Prueba_V
     */
    int x, y;
    
    public TipoPrueba_V() {
        initComponents();
        
        txt_id_TP.setVisible(false);
        txt_TP.setVisible(false);
        
        Tipo_Prueba TP = new Tipo_Prueba(txt_id_TP, txt_TP, tbl_TP, txt_BuscarTP);
        TP.Actualizar_Tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Prueba = new javax.swing.JPanel();
        txt_id_TP = new javax.swing.JTextField();
        txt_TP = new javax.swing.JTextField();
        jLabel_BuscarTP = new javax.swing.JLabel();
        txt_BuscarTP = new javax.swing.JTextField();
        jScrollPane32 = new javax.swing.JScrollPane();
        tbl_TP = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel_Titulo = new javax.swing.JLabel();
        Movimiento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Prueba.setBackground(new java.awt.Color(28, 27, 33));
        Prueba.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id_TP.setBackground(new java.awt.Color(40, 41, 46));
        txt_id_TP.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_TP.setBorder(null);
        txt_id_TP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_TPActionPerformed(evt);
            }
        });
        Prueba.add(txt_id_TP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 140, 20));

        txt_TP.setBackground(new java.awt.Color(40, 41, 46));
        txt_TP.setForeground(new java.awt.Color(255, 255, 255));
        txt_TP.setBorder(null);
        txt_TP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TPActionPerformed(evt);
            }
        });
        Prueba.add(txt_TP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 140, 20));

        jLabel_BuscarTP.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_BuscarTP.setText("Buscar");
        jLabel_BuscarTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BuscarTPMouseClicked(evt);
            }
        });
        Prueba.add(jLabel_BuscarTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 50, 20));

        txt_BuscarTP.setBackground(new java.awt.Color(40, 41, 46));
        txt_BuscarTP.setForeground(new java.awt.Color(255, 255, 255));
        txt_BuscarTP.setBorder(null);
        txt_BuscarTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BuscarTPActionPerformed(evt);
            }
        });
        txt_BuscarTP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarTPKeyReleased(evt);
            }
        });
        Prueba.add(txt_BuscarTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 270, 20));

        tbl_TP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_TP.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_TP.setSelectionBackground(new java.awt.Color(0, 204, 255));
        tbl_TP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_TPMouseClicked(evt);
            }
        });
        jScrollPane32.setViewportView(tbl_TP);

        Prueba.add(jScrollPane32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 600, 200));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_D.png"))); // NOI18N
        Prueba.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jLabel_Titulo.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Tipo Prueba");
        Prueba.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 250, 40));

        Movimiento.setBackground(new java.awt.Color(28, 27, 33));
        Movimiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovimientoMouseDragged(evt);
            }
        });
        Movimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovimientoMousePressed(evt);
            }
        });
        Movimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Movimiento.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 20, 30));

        Prueba.add(Movimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 40));

        getContentPane().add(Prueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_TPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_TPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_TPActionPerformed

    private void txt_TPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TPActionPerformed

    private void jLabel_BuscarTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BuscarTPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_BuscarTPMouseClicked

    private void txt_BuscarTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BuscarTPActionPerformed
        Tipo_Prueba TP = new Tipo_Prueba(txt_id_TP, txt_TP, tbl_TP, txt_BuscarTP);
        TP.Buscar_TP(txt_BuscarTP.getText());
       
    }//GEN-LAST:event_txt_BuscarTPActionPerformed

    private void txt_BuscarTPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarTPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BuscarTPKeyReleased

    private void tbl_TPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_TPMouseClicked
        int Seleccion = tbl_TP.rowAtPoint(evt.getPoint());
        txt_id_TP.setText(String.valueOf(tbl_TP.getValueAt(Seleccion, 0)));
        txt_TP.setText(String.valueOf(tbl_TP.getValueAt(Seleccion, 1)));

        
    }//GEN-LAST:event_tbl_TPMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void MovimientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_MovimientoMouseDragged

    private void MovimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovimientoMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_MovimientoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoPrueba_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoPrueba_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoPrueba_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoPrueba_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoPrueba_V().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Movimiento;
    private javax.swing.JPanel Prueba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_BuscarTP;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JTable tbl_TP;
    private javax.swing.JTextField txt_BuscarTP;
    private javax.swing.JTextField txt_TP;
    private javax.swing.JTextField txt_id_TP;
    // End of variables declaration//GEN-END:variables
}
